// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts_imports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByImportRun = `-- name: CountTransactionsByImportRun :one
SELECT COUNT(*)::bigint AS count
FROM transactions
WHERE import_run_id = $1
`

func (q *Queries) CountTransactionsByImportRun(ctx context.Context, importRunID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByImportRun, importRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    display_name,
    bank,
    currency,
    order_account,
    masked_identifier
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, display_name, bank, currency, order_account, masked_identifier, created_at, updated_at
`

type CreateAccountParams struct {
	DisplayName      string      `json:"display_name"`
	Bank             string      `json:"bank"`
	Currency         string      `json:"currency"`
	OrderAccount     pgtype.Text `json:"order_account"`
	MaskedIdentifier string      `json:"masked_identifier"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.DisplayName,
		arg.Bank,
		arg.Currency,
		arg.OrderAccount,
		arg.MaskedIdentifier,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bank,
		&i.Currency,
		&i.OrderAccount,
		&i.MaskedIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImportRun = `-- name: CreateImportRun :one
INSERT INTO import_runs (
    account_id,
    source_filename,
    file_hash,
    parser_name,
    parser_version,
    status,
    period_from,
    period_to,
    row_total,
    row_valid,
    row_invalid,
    row_inserted,
    row_duplicate,
    warnings,
    committed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, account_id, source_filename, file_hash, parser_name, parser_version, status, period_from, period_to, row_total, row_valid, row_invalid, row_inserted, row_duplicate, warnings, created_at, committed_at, rolled_back_at
`

type CreateImportRunParams struct {
	AccountID      uuid.UUID          `json:"account_id"`
	SourceFilename string             `json:"source_filename"`
	FileHash       string             `json:"file_hash"`
	ParserName     string             `json:"parser_name"`
	ParserVersion  string             `json:"parser_version"`
	Status         string             `json:"status"`
	PeriodFrom     pgtype.Date        `json:"period_from"`
	PeriodTo       pgtype.Date        `json:"period_to"`
	RowTotal       int32              `json:"row_total"`
	RowValid       int32              `json:"row_valid"`
	RowInvalid     int32              `json:"row_invalid"`
	RowInserted    int32              `json:"row_inserted"`
	RowDuplicate   int32              `json:"row_duplicate"`
	Warnings       []byte             `json:"warnings"`
	CommittedAt    pgtype.Timestamptz `json:"committed_at"`
}

func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error) {
	row := q.db.QueryRow(ctx, createImportRun,
		arg.AccountID,
		arg.SourceFilename,
		arg.FileHash,
		arg.ParserName,
		arg.ParserVersion,
		arg.Status,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.RowTotal,
		arg.RowValid,
		arg.RowInvalid,
		arg.RowInserted,
		arg.RowDuplicate,
		arg.Warnings,
		arg.CommittedAt,
	)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SourceFilename,
		&i.FileHash,
		&i.ParserName,
		&i.ParserVersion,
		&i.Status,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.RowTotal,
		&i.RowValid,
		&i.RowInvalid,
		&i.RowInserted,
		&i.RowDuplicate,
		&i.Warnings,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.RolledBackAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, display_name, bank, currency, order_account, masked_identifier, created_at, updated_at FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bank,
		&i.Currency,
		&i.OrderAccount,
		&i.MaskedIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByOrderAccount = `-- name: GetAccountByOrderAccount :one
SELECT id, display_name, bank, currency, order_account, masked_identifier, created_at, updated_at FROM accounts
WHERE order_account = $1
`

func (q *Queries) GetAccountByOrderAccount(ctx context.Context, orderAccount pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByOrderAccount, orderAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Bank,
		&i.Currency,
		&i.OrderAccount,
		&i.MaskedIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportRun = `-- name: GetImportRun :one
SELECT id, account_id, source_filename, file_hash, parser_name, parser_version, status, period_from, period_to, row_total, row_valid, row_invalid, row_inserted, row_duplicate, warnings, created_at, committed_at, rolled_back_at FROM import_runs
WHERE id = $1
`

func (q *Queries) GetImportRun(ctx context.Context, id uuid.UUID) (ImportRun, error) {
	row := q.db.QueryRow(ctx, getImportRun, id)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SourceFilename,
		&i.FileHash,
		&i.ParserName,
		&i.ParserVersion,
		&i.Status,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.RowTotal,
		&i.RowValid,
		&i.RowInvalid,
		&i.RowInserted,
		&i.RowDuplicate,
		&i.Warnings,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.RolledBackAt,
	)
	return i, err
}

const updateImportRunCounts = `-- name: UpdateImportRunCounts :one
UPDATE import_runs
SET
    row_inserted = $2,
    row_duplicate = $3,
    committed_at = COALESCE(committed_at, now())
WHERE id = $1
RETURNING id, account_id, source_filename, file_hash, parser_name, parser_version, status, period_from, period_to, row_total, row_valid, row_invalid, row_inserted, row_duplicate, warnings, created_at, committed_at, rolled_back_at
`

type UpdateImportRunCountsParams struct {
	ID           uuid.UUID `json:"id"`
	RowInserted  int32     `json:"row_inserted"`
	RowDuplicate int32     `json:"row_duplicate"`
}

func (q *Queries) UpdateImportRunCounts(ctx context.Context, arg UpdateImportRunCountsParams) (ImportRun, error) {
	row := q.db.QueryRow(ctx, updateImportRunCounts, arg.ID, arg.RowInserted, arg.RowDuplicate)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.SourceFilename,
		&i.FileHash,
		&i.ParserName,
		&i.ParserVersion,
		&i.Status,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.RowTotal,
		&i.RowValid,
		&i.RowInvalid,
		&i.RowInserted,
		&i.RowDuplicate,
		&i.Warnings,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.RolledBackAt,
	)
	return i, err
}
