// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimHousehold = `-- name: ClaimHousehold :one
UPDATE households
SET claimed_at = now()
WHERE id = $1 AND claimed_at IS NULL
RETURNING id, name, claimed_at, created_at
`

func (q *Queries) ClaimHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, claimHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name)
VALUES ($1)
RETURNING id, name, claimed_at, created_at
`

func (q *Queries) CreateHousehold(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO household_memberships (household_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING household_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (HouseholdMembership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.HouseholdID, arg.UserID, arg.Role)
	var i HouseholdMembership
	err := row.Scan(
		&i.HouseholdID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthLoginState = `-- name: CreateOAuthLoginState :one
INSERT INTO oauth_login_states (state, nonce, code_verifier, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING state, nonce, code_verifier, expires_at, created_at
`

type CreateOAuthLoginStateParams struct {
	State        string             `json:"state"`
	Nonce        string             `json:"nonce"`
	CodeVerifier string             `json:"code_verifier"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthLoginState(ctx context.Context, arg CreateOAuthLoginStateParams) (OauthLoginState, error) {
	row := q.db.QueryRow(ctx, createOAuthLoginState,
		arg.State,
		arg.Nonce,
		arg.CodeVerifier,
		arg.ExpiresAt,
	)
	var i OauthLoginState
	err := row.Scan(
		&i.State,
		&i.Nonce,
		&i.CodeVerifier,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    token_hash,
    expires_at,
    absolute_expires_at,
    user_agent,
    ip
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, token_hash, expires_at, absolute_expires_at, created_at, revoked_at, user_agent, ip
`

type CreateSessionParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	TokenHash         []byte             `json:"token_hash"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	UserAgent         string             `json:"user_agent"`
	Ip                *netip.Addr        `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name, given_name, picture_url, preferred_locale)
VALUES ($1, $2, $3, $4)
RETURNING id, display_name, created_at, given_name, picture_url, preferred_locale
`

type CreateUserParams struct {
	DisplayName     string      `json:"display_name"`
	GivenName       pgtype.Text `json:"given_name"`
	PictureUrl      pgtype.Text `json:"picture_url"`
	PreferredLocale string      `json:"preferred_locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.GivenName,
		arg.PictureUrl,
		arg.PreferredLocale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.GivenName,
		&i.PictureUrl,
		&i.PreferredLocale,
	)
	return i, err
}

const deleteExpiredOAuthLoginStates = `-- name: DeleteExpiredOAuthLoginStates :exec
DELETE FROM oauth_login_states
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthLoginStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthLoginStates)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE revoked_at IS NOT NULL
   OR expires_at < now()
   OR absolute_expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteOAuthLoginState = `-- name: DeleteOAuthLoginState :exec
DELETE FROM oauth_login_states
WHERE state = $1
`

func (q *Queries) DeleteOAuthLoginState(ctx context.Context, state string) error {
	_, err := q.db.Exec(ctx, deleteOAuthLoginState, state)
	return err
}

const getAuthIdentitiesByUser = `-- name: GetAuthIdentitiesByUser :many
SELECT id, user_id, provider, provider_subject, email, email_verified, created_at FROM auth_identities
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, getAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Email,
			&i.EmailVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentityByProviderSubject = `-- name: GetAuthIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_subject, email, email_verified, created_at FROM auth_identities
WHERE provider = $1 AND provider_subject = $2
`

type GetAuthIdentityByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetAuthIdentityByProviderSubject(ctx context.Context, arg GetAuthIdentityByProviderSubjectParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getFirstHousehold = `-- name: GetFirstHousehold :one
SELECT id, name, claimed_at, created_at FROM households
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetFirstHousehold(ctx context.Context) (Household, error) {
	row := q.db.QueryRow(ctx, getFirstHousehold)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, claimed_at, created_at FROM households
WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHouseholdByName = `-- name: GetHouseholdByName :one
SELECT id, name, claimed_at, created_at FROM households
WHERE name = $1
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetHouseholdByName(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByName, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipsByUser = `-- name: GetMembershipsByUser :many
SELECT household_id, user_id, role, created_at FROM household_memberships
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]HouseholdMembership, error) {
	rows, err := q.db.Query(ctx, getMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HouseholdMembership{}
	for rows.Next() {
		var i HouseholdMembership
		if err := rows.Scan(
			&i.HouseholdID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthLoginState = `-- name: GetOAuthLoginState :one
SELECT state, nonce, code_verifier, expires_at, created_at FROM oauth_login_states
WHERE state = $1
`

func (q *Queries) GetOAuthLoginState(ctx context.Context, state string) (OauthLoginState, error) {
	row := q.db.QueryRow(ctx, getOAuthLoginState, state)
	var i OauthLoginState
	err := row.Scan(
		&i.State,
		&i.Nonce,
		&i.CodeVerifier,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, absolute_expires_at, created_at, revoked_at, user_agent, ip FROM sessions
WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getUnclaimedSeedHousehold = `-- name: GetUnclaimedSeedHousehold :one
SELECT id, name, claimed_at, created_at FROM households
WHERE claimed_at IS NULL
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetUnclaimedSeedHousehold(ctx context.Context) (Household, error) {
	row := q.db.QueryRow(ctx, getUnclaimedSeedHousehold)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, created_at, given_name, picture_url, preferred_locale FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.GivenName,
		&i.PictureUrl,
		&i.PreferredLocale,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, absolute_expires_at, created_at, revoked_at, user_agent, ip
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, revokeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET expires_at = $2
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, expires_at, absolute_expires_at, created_at, revoked_at, user_agent, ip
`

type TouchSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const updateUserGoogleProfile = `-- name: UpdateUserGoogleProfile :one
UPDATE users
SET
    given_name = CASE
        WHEN given_name IS NULL AND NULLIF($1::text, '') IS NOT NULL
            THEN NULLIF($1::text, '')
        ELSE given_name
    END,
    picture_url = NULLIF($2::text, '')
WHERE id = $3
RETURNING id, display_name, created_at, given_name, picture_url, preferred_locale
`

type UpdateUserGoogleProfileParams struct {
	GivenName  string    `json:"given_name"`
	PictureUrl string    `json:"picture_url"`
	ID         uuid.UUID `json:"id"`
}

// Refresh picture from Google; fill given_name only when still unset.
func (q *Queries) UpdateUserGoogleProfile(ctx context.Context, arg UpdateUserGoogleProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGoogleProfile, arg.GivenName, arg.PictureUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.GivenName,
		&i.PictureUrl,
		&i.PreferredLocale,
	)
	return i, err
}

const upsertAuthIdentity = `-- name: UpsertAuthIdentity :one
INSERT INTO auth_identities (user_id, provider, provider_subject, email, email_verified)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_subject) DO UPDATE
SET
    email = EXCLUDED.email,
    email_verified = EXCLUDED.email_verified
RETURNING id, user_id, provider, provider_subject, email, email_verified, created_at
`

type UpsertAuthIdentityParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ProviderSubject string    `json:"provider_subject"`
	Email           string    `json:"email"`
	EmailVerified   bool      `json:"email_verified"`
}

func (q *Queries) UpsertAuthIdentity(ctx context.Context, arg UpsertAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, upsertAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.EmailVerified,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}
