// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: baselines.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const confirmFinancialBaseline = `-- name: ConfirmFinancialBaseline :one
UPDATE financial_baselines
SET
    status = 'confirmed',
    confirmed_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'draft'
RETURNING id, period_from, period_to, algorithm_version, status, regular_monthly_income, monthly_fixed_costs, monthly_irregular_costs, avg_variable_spend, sustainable_free_cashflow, confidence, assumptions, evidence, confirmed_at, created_at, updated_at
`

func (q *Queries) ConfirmFinancialBaseline(ctx context.Context, id uuid.UUID) (FinancialBaseline, error) {
	row := q.db.QueryRow(ctx, confirmFinancialBaseline, id)
	var i FinancialBaseline
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.AlgorithmVersion,
		&i.Status,
		&i.RegularMonthlyIncome,
		&i.MonthlyFixedCosts,
		&i.MonthlyIrregularCosts,
		&i.AvgVariableSpend,
		&i.SustainableFreeCashflow,
		&i.Confidence,
		&i.Assumptions,
		&i.Evidence,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentFinancialBaseline = `-- name: GetCurrentFinancialBaseline :one
SELECT id, period_from, period_to, algorithm_version, status, regular_monthly_income, monthly_fixed_costs, monthly_irregular_costs, avg_variable_spend, sustainable_free_cashflow, confidence, assumptions, evidence, confirmed_at, created_at, updated_at
FROM financial_baselines
WHERE status IN ('draft', 'confirmed')
ORDER BY
    CASE status WHEN 'confirmed' THEN 0 WHEN 'draft' THEN 1 ELSE 2 END,
    created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentFinancialBaseline(ctx context.Context) (FinancialBaseline, error) {
	row := q.db.QueryRow(ctx, getCurrentFinancialBaseline)
	var i FinancialBaseline
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.AlgorithmVersion,
		&i.Status,
		&i.RegularMonthlyIncome,
		&i.MonthlyFixedCosts,
		&i.MonthlyIrregularCosts,
		&i.AvgVariableSpend,
		&i.SustainableFreeCashflow,
		&i.Confidence,
		&i.Assumptions,
		&i.Evidence,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinancialBaseline = `-- name: GetFinancialBaseline :one
SELECT id, period_from, period_to, algorithm_version, status, regular_monthly_income, monthly_fixed_costs, monthly_irregular_costs, avg_variable_spend, sustainable_free_cashflow, confidence, assumptions, evidence, confirmed_at, created_at, updated_at
FROM financial_baselines
WHERE id = $1
`

func (q *Queries) GetFinancialBaseline(ctx context.Context, id uuid.UUID) (FinancialBaseline, error) {
	row := q.db.QueryRow(ctx, getFinancialBaseline, id)
	var i FinancialBaseline
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.AlgorithmVersion,
		&i.Status,
		&i.RegularMonthlyIncome,
		&i.MonthlyFixedCosts,
		&i.MonthlyIrregularCosts,
		&i.AvgVariableSpend,
		&i.SustainableFreeCashflow,
		&i.Confidence,
		&i.Assumptions,
		&i.Evidence,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBaselineAdjustment = `-- name: InsertBaselineAdjustment :one
INSERT INTO baseline_adjustments (
    baseline_id,
    metric_key,
    previous_value,
    new_value,
    reason
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, baseline_id, metric_key, previous_value, new_value, reason, created_at
`

type InsertBaselineAdjustmentParams struct {
	BaselineID    uuid.UUID       `json:"baseline_id"`
	MetricKey     string          `json:"metric_key"`
	PreviousValue decimal.Decimal `json:"previous_value"`
	NewValue      decimal.Decimal `json:"new_value"`
	Reason        string          `json:"reason"`
}

func (q *Queries) InsertBaselineAdjustment(ctx context.Context, arg InsertBaselineAdjustmentParams) (BaselineAdjustment, error) {
	row := q.db.QueryRow(ctx, insertBaselineAdjustment,
		arg.BaselineID,
		arg.MetricKey,
		arg.PreviousValue,
		arg.NewValue,
		arg.Reason,
	)
	var i BaselineAdjustment
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.MetricKey,
		&i.PreviousValue,
		&i.NewValue,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertFinancialBaseline = `-- name: InsertFinancialBaseline :one
INSERT INTO financial_baselines (
    period_from,
    period_to,
    algorithm_version,
    status,
    regular_monthly_income,
    monthly_fixed_costs,
    monthly_irregular_costs,
    avg_variable_spend,
    sustainable_free_cashflow,
    confidence,
    assumptions,
    evidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, period_from, period_to, algorithm_version, status, regular_monthly_income, monthly_fixed_costs, monthly_irregular_costs, avg_variable_spend, sustainable_free_cashflow, confidence, assumptions, evidence, confirmed_at, created_at, updated_at
`

type InsertFinancialBaselineParams struct {
	PeriodFrom              pgtype.Date     `json:"period_from"`
	PeriodTo                pgtype.Date     `json:"period_to"`
	AlgorithmVersion        string          `json:"algorithm_version"`
	Status                  string          `json:"status"`
	RegularMonthlyIncome    decimal.Decimal `json:"regular_monthly_income"`
	MonthlyFixedCosts       decimal.Decimal `json:"monthly_fixed_costs"`
	MonthlyIrregularCosts   decimal.Decimal `json:"monthly_irregular_costs"`
	AvgVariableSpend        decimal.Decimal `json:"avg_variable_spend"`
	SustainableFreeCashflow decimal.Decimal `json:"sustainable_free_cashflow"`
	Confidence              string          `json:"confidence"`
	Assumptions             []byte          `json:"assumptions"`
	Evidence                []byte          `json:"evidence"`
}

func (q *Queries) InsertFinancialBaseline(ctx context.Context, arg InsertFinancialBaselineParams) (FinancialBaseline, error) {
	row := q.db.QueryRow(ctx, insertFinancialBaseline,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.AlgorithmVersion,
		arg.Status,
		arg.RegularMonthlyIncome,
		arg.MonthlyFixedCosts,
		arg.MonthlyIrregularCosts,
		arg.AvgVariableSpend,
		arg.SustainableFreeCashflow,
		arg.Confidence,
		arg.Assumptions,
		arg.Evidence,
	)
	var i FinancialBaseline
	err := row.Scan(
		&i.ID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.AlgorithmVersion,
		&i.Status,
		&i.RegularMonthlyIncome,
		&i.MonthlyFixedCosts,
		&i.MonthlyIrregularCosts,
		&i.AvgVariableSpend,
		&i.SustainableFreeCashflow,
		&i.Confidence,
		&i.Assumptions,
		&i.Evidence,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supersedeOpenFinancialBaselines = `-- name: SupersedeOpenFinancialBaselines :exec
UPDATE financial_baselines
SET
    status = 'superseded',
    updated_at = now()
WHERE status IN ('draft', 'confirmed')
`

func (q *Queries) SupersedeOpenFinancialBaselines(ctx context.Context) error {
	_, err := q.db.Exec(ctx, supersedeOpenFinancialBaselines)
	return err
}
