// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countClassificationsByCategorySlug = `-- name: CountClassificationsByCategorySlug :many
SELECT c.slug, COUNT(*)::bigint AS count
FROM transaction_classifications tc
JOIN categories c ON c.id = tc.category_id
GROUP BY c.slug
ORDER BY c.slug
`

type CountClassificationsByCategorySlugRow struct {
	Slug  string `json:"slug"`
	Count int64  `json:"count"`
}

func (q *Queries) CountClassificationsByCategorySlug(ctx context.Context) ([]CountClassificationsByCategorySlugRow, error) {
	rows, err := q.db.Query(ctx, countClassificationsByCategorySlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountClassificationsByCategorySlugRow{}
	for rows.Next() {
		var i CountClassificationsByCategorySlugRow
		if err := rows.Scan(&i.Slug, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countClassificationsBySource = `-- name: CountClassificationsBySource :many
SELECT source, COUNT(*)::bigint AS count
FROM transaction_classifications
GROUP BY source
ORDER BY source
`

type CountClassificationsBySourceRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountClassificationsBySource(ctx context.Context) ([]CountClassificationsBySourceRow, error) {
	rows, err := q.db.Query(ctx, countClassificationsBySource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountClassificationsBySourceRow{}
	for rows.Next() {
		var i CountClassificationsBySourceRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedTransferTransactionIDs = `-- name: ListConfirmedTransferTransactionIDs :many
SELECT tx_out_id AS transaction_id FROM transfer_pairs WHERE status = 'confirmed'
UNION
SELECT tx_in_id AS transaction_id FROM transfer_pairs WHERE status = 'confirmed'
`

func (q *Queries) ListConfirmedTransferTransactionIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConfirmedTransferTransactionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var transaction_id uuid.UUID
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForClassify = `-- name: ListTransactionsForClassify :many
SELECT
    id,
    counterparty,
    purpose,
    booking_text,
    amount
FROM transactions
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForClassifyRow struct {
	ID           uuid.UUID       `json:"id"`
	Counterparty string          `json:"counterparty"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Amount       decimal.Decimal `json:"amount"`
}

func (q *Queries) ListTransactionsForClassify(ctx context.Context) ([]ListTransactionsForClassifyRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForClassify)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForClassifyRow{}
	for rows.Next() {
		var i ListTransactionsForClassifyRow
		if err := rows.Scan(
			&i.ID,
			&i.Counterparty,
			&i.Purpose,
			&i.BookingText,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTransactionClassification = `-- name: UpsertTransactionClassification :one
INSERT INTO transaction_classifications (
    transaction_id,
    category_id,
    merchant_id,
    source,
    confidence,
    algorithm_version,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (transaction_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    merchant_id = EXCLUDED.merchant_id,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    algorithm_version = EXCLUDED.algorithm_version,
    updated_at = now()
WHERE transaction_classifications.source <> 'user_rule'
RETURNING transaction_id, category_id, merchant_id, source, confidence, algorithm_version, updated_at
`

type UpsertTransactionClassificationParams struct {
	TransactionID    uuid.UUID   `json:"transaction_id"`
	CategoryID       uuid.UUID   `json:"category_id"`
	MerchantID       pgtype.UUID `json:"merchant_id"`
	Source           string      `json:"source"`
	Confidence       string      `json:"confidence"`
	AlgorithmVersion string      `json:"algorithm_version"`
}

func (q *Queries) UpsertTransactionClassification(ctx context.Context, arg UpsertTransactionClassificationParams) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, upsertTransactionClassification,
		arg.TransactionID,
		arg.CategoryID,
		arg.MerchantID,
		arg.Source,
		arg.Confidence,
		arg.AlgorithmVersion,
	)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}
