// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countClassificationsBySource = `-- name: CountClassificationsBySource :many
SELECT tc.source, COUNT(*)::bigint AS count
FROM transaction_classifications tc
JOIN transactions t ON t.id = tc.transaction_id
WHERE t.household_id = $1
GROUP BY tc.source
ORDER BY tc.source
`

type CountClassificationsBySourceRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountClassificationsBySource(ctx context.Context, householdID uuid.UUID) ([]CountClassificationsBySourceRow, error) {
	rows, err := q.db.Query(ctx, countClassificationsBySource, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountClassificationsBySourceRow{}
	for rows.Next() {
		var i CountClassificationsBySourceRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createClassificationRule = `-- name: CreateClassificationRule :one
INSERT INTO classification_rules (
    household_id,
    priority,
    merchant_id,
    pattern,
    category_id,
    created_from_transaction_id,
    confidence,
    is_system
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at, confidence, is_system, household_id
`

type CreateClassificationRuleParams struct {
	HouseholdID              uuid.UUID   `json:"household_id"`
	Priority                 int32       `json:"priority"`
	MerchantID               pgtype.UUID `json:"merchant_id"`
	Pattern                  pgtype.Text `json:"pattern"`
	CategoryID               uuid.UUID   `json:"category_id"`
	CreatedFromTransactionID pgtype.UUID `json:"created_from_transaction_id"`
	Confidence               string      `json:"confidence"`
	IsSystem                 bool        `json:"is_system"`
}

func (q *Queries) CreateClassificationRule(ctx context.Context, arg CreateClassificationRuleParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, createClassificationRule,
		arg.HouseholdID,
		arg.Priority,
		arg.MerchantID,
		arg.Pattern,
		arg.CategoryID,
		arg.CreatedFromTransactionID,
		arg.Confidence,
		arg.IsSystem,
	)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
		&i.Confidence,
		&i.IsSystem,
		&i.HouseholdID,
	)
	return i, err
}

const forceUpsertTransactionClassification = `-- name: ForceUpsertTransactionClassification :one
INSERT INTO transaction_classifications (
    transaction_id,
    category_id,
    merchant_id,
    source,
    confidence,
    algorithm_version,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (transaction_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    merchant_id = EXCLUDED.merchant_id,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    algorithm_version = EXCLUDED.algorithm_version,
    updated_at = now()
RETURNING transaction_id, category_id, merchant_id, source, confidence, algorithm_version, updated_at
`

type ForceUpsertTransactionClassificationParams struct {
	TransactionID    uuid.UUID   `json:"transaction_id"`
	CategoryID       uuid.UUID   `json:"category_id"`
	MerchantID       pgtype.UUID `json:"merchant_id"`
	Source           string      `json:"source"`
	Confidence       string      `json:"confidence"`
	AlgorithmVersion string      `json:"algorithm_version"`
}

func (q *Queries) ForceUpsertTransactionClassification(ctx context.Context, arg ForceUpsertTransactionClassificationParams) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, forceUpsertTransactionClassification,
		arg.TransactionID,
		arg.CategoryID,
		arg.MerchantID,
		arg.Source,
		arg.Confidence,
		arg.AlgorithmVersion,
	)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassificationRuleByMerchant = `-- name: GetClassificationRuleByMerchant :one
SELECT id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at, confidence, is_system, household_id
FROM classification_rules
WHERE merchant_id = $1 AND household_id = $2
`

type GetClassificationRuleByMerchantParams struct {
	MerchantID  pgtype.UUID `json:"merchant_id"`
	HouseholdID uuid.UUID   `json:"household_id"`
}

func (q *Queries) GetClassificationRuleByMerchant(ctx context.Context, arg GetClassificationRuleByMerchantParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, getClassificationRuleByMerchant, arg.MerchantID, arg.HouseholdID)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
		&i.Confidence,
		&i.IsSystem,
		&i.HouseholdID,
	)
	return i, err
}

const getClassificationRuleByPattern = `-- name: GetClassificationRuleByPattern :one
SELECT id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at, confidence, is_system, household_id
FROM classification_rules
WHERE merchant_id IS NULL
  AND lower(pattern) = lower($1)
  AND household_id = $2
`

type GetClassificationRuleByPatternParams struct {
	Pattern     string    `json:"pattern"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetClassificationRuleByPattern(ctx context.Context, arg GetClassificationRuleByPatternParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, getClassificationRuleByPattern, arg.Pattern, arg.HouseholdID)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
		&i.Confidence,
		&i.IsSystem,
		&i.HouseholdID,
	)
	return i, err
}

const getTransactionClassification = `-- name: GetTransactionClassification :one
SELECT tc.transaction_id, tc.category_id, tc.merchant_id, tc.source, tc.confidence, tc.algorithm_version, tc.updated_at
FROM transaction_classifications tc
JOIN transactions t ON t.id = tc.transaction_id
WHERE tc.transaction_id = $1 AND t.household_id = $2
`

type GetTransactionClassificationParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	HouseholdID   uuid.UUID `json:"household_id"`
}

func (q *Queries) GetTransactionClassification(ctx context.Context, arg GetTransactionClassificationParams) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, getTransactionClassification, arg.TransactionID, arg.HouseholdID)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionForClassify = `-- name: GetTransactionForClassify :one
SELECT
    id,
    counterparty,
    purpose,
    booking_text,
    amount
FROM transactions
WHERE id = $1 AND household_id = $2
`

type GetTransactionForClassifyParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

type GetTransactionForClassifyRow struct {
	ID           uuid.UUID       `json:"id"`
	Counterparty string          `json:"counterparty"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Amount       decimal.Decimal `json:"amount"`
}

func (q *Queries) GetTransactionForClassify(ctx context.Context, arg GetTransactionForClassifyParams) (GetTransactionForClassifyRow, error) {
	row := q.db.QueryRow(ctx, getTransactionForClassify, arg.ID, arg.HouseholdID)
	var i GetTransactionForClassifyRow
	err := row.Scan(
		&i.ID,
		&i.Counterparty,
		&i.Purpose,
		&i.BookingText,
		&i.Amount,
	)
	return i, err
}

const listClassificationQueue = `-- name: ListClassificationQueue :many
SELECT
    t.id AS transaction_id,
    t.booking_date,
    t.amount,
    t.counterparty,
    t.purpose,
    t.booking_text,
    c.slug AS category_slug,
    c.display_name AS category_name,
    tc.source,
    tc.confidence,
    m.id AS merchant_id,
    COALESCE(m.display_name, '') AS merchant_name
FROM transaction_classifications tc
JOIN transactions t ON t.id = tc.transaction_id
JOIN categories c ON c.id = tc.category_id
LEFT JOIN merchants m ON m.id = tc.merchant_id
WHERE t.household_id = $1
  AND tc.source <> 'user_rule'
  AND c.slug <> 'transfer'
  AND t.one_off = false
  AND (
    tc.source = 'unresolved'
    OR tc.confidence = 'low'
  )
ORDER BY ABS(t.amount) DESC, t.booking_date DESC, t.id ASC
LIMIT 100
`

type ListClassificationQueueRow struct {
	TransactionID uuid.UUID       `json:"transaction_id"`
	BookingDate   pgtype.Date     `json:"booking_date"`
	Amount        decimal.Decimal `json:"amount"`
	Counterparty  string          `json:"counterparty"`
	Purpose       string          `json:"purpose"`
	BookingText   string          `json:"booking_text"`
	CategorySlug  string          `json:"category_slug"`
	CategoryName  string          `json:"category_name"`
	Source        string          `json:"source"`
	Confidence    string          `json:"confidence"`
	MerchantID    pgtype.UUID     `json:"merchant_id"`
	MerchantName  string          `json:"merchant_name"`
}

func (q *Queries) ListClassificationQueue(ctx context.Context, householdID uuid.UUID) ([]ListClassificationQueueRow, error) {
	rows, err := q.db.Query(ctx, listClassificationQueue, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassificationQueueRow{}
	for rows.Next() {
		var i ListClassificationQueueRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.BookingDate,
			&i.Amount,
			&i.Counterparty,
			&i.Purpose,
			&i.BookingText,
			&i.CategorySlug,
			&i.CategoryName,
			&i.Source,
			&i.Confidence,
			&i.MerchantID,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassificationRules = `-- name: ListClassificationRules :many
SELECT id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at, confidence, is_system, household_id
FROM classification_rules
WHERE household_id = $1
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListClassificationRules(ctx context.Context, householdID uuid.UUID) ([]ClassificationRule, error) {
	rows, err := q.db.Query(ctx, listClassificationRules, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassificationRule{}
	for rows.Next() {
		var i ClassificationRule
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.MerchantID,
			&i.Pattern,
			&i.CategoryID,
			&i.CreatedFromTransactionID,
			&i.CreatedAt,
			&i.Confidence,
			&i.IsSystem,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedTransferTransactionIDs = `-- name: ListConfirmedTransferTransactionIDs :many
SELECT p.tx_out_id AS transaction_id
FROM transfer_pairs p
WHERE p.status = 'confirmed' AND p.household_id = $1
UNION
SELECT p.tx_in_id AS transaction_id
FROM transfer_pairs p
WHERE p.status = 'confirmed' AND p.household_id = $1
`

func (q *Queries) ListConfirmedTransferTransactionIDs(ctx context.Context, householdID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConfirmedTransferTransactionIDs, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var transaction_id uuid.UUID
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForClassify = `-- name: ListTransactionsForClassify :many
SELECT
    id,
    counterparty,
    purpose,
    booking_text,
    amount
FROM transactions
WHERE household_id = $1
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForClassifyRow struct {
	ID           uuid.UUID       `json:"id"`
	Counterparty string          `json:"counterparty"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Amount       decimal.Decimal `json:"amount"`
}

func (q *Queries) ListTransactionsForClassify(ctx context.Context, householdID uuid.UUID) ([]ListTransactionsForClassifyRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForClassify, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForClassifyRow{}
	for rows.Next() {
		var i ListTransactionsForClassifyRow
		if err := rows.Scan(
			&i.ID,
			&i.Counterparty,
			&i.Purpose,
			&i.BookingText,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassificationRuleCategory = `-- name: UpdateClassificationRuleCategory :one
UPDATE classification_rules
SET
    category_id = $3,
    created_from_transaction_id = $4,
    priority = $5
WHERE id = $1 AND household_id = $2
RETURNING id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at, confidence, is_system, household_id
`

type UpdateClassificationRuleCategoryParams struct {
	ID                       uuid.UUID   `json:"id"`
	HouseholdID              uuid.UUID   `json:"household_id"`
	CategoryID               uuid.UUID   `json:"category_id"`
	CreatedFromTransactionID pgtype.UUID `json:"created_from_transaction_id"`
	Priority                 int32       `json:"priority"`
}

func (q *Queries) UpdateClassificationRuleCategory(ctx context.Context, arg UpdateClassificationRuleCategoryParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, updateClassificationRuleCategory,
		arg.ID,
		arg.HouseholdID,
		arg.CategoryID,
		arg.CreatedFromTransactionID,
		arg.Priority,
	)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
		&i.Confidence,
		&i.IsSystem,
		&i.HouseholdID,
	)
	return i, err
}

const updateMerchantDefaultCategory = `-- name: UpdateMerchantDefaultCategory :one
UPDATE merchants
SET default_category_id = $3
WHERE id = $1 AND household_id = $2
RETURNING id, display_name, default_category_id, created_at, household_id
`

type UpdateMerchantDefaultCategoryParams struct {
	ID                uuid.UUID   `json:"id"`
	HouseholdID       uuid.UUID   `json:"household_id"`
	DefaultCategoryID pgtype.UUID `json:"default_category_id"`
}

func (q *Queries) UpdateMerchantDefaultCategory(ctx context.Context, arg UpdateMerchantDefaultCategoryParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantDefaultCategory, arg.ID, arg.HouseholdID, arg.DefaultCategoryID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DefaultCategoryID,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const upsertSystemPatternRule = `-- name: UpsertSystemPatternRule :one
INSERT INTO classification_rules (
    household_id,
    priority,
    merchant_id,
    pattern,
    category_id,
    created_from_transaction_id,
    confidence,
    is_system
) VALUES (
    $1,
    $2,
    NULL,
    $3,
    $4,
    NULL,
    $5,
    true
)
ON CONFLICT ((lower(pattern))) WHERE merchant_id IS NULL AND pattern IS NOT NULL
DO UPDATE SET
    priority = EXCLUDED.priority,
    category_id = EXCLUDED.category_id,
    confidence = EXCLUDED.confidence,
    is_system = true
RETURNING id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at, confidence, is_system, household_id
`

type UpsertSystemPatternRuleParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Priority    int32       `json:"priority"`
	Pattern     pgtype.Text `json:"pattern"`
	CategoryID  uuid.UUID   `json:"category_id"`
	Confidence  string      `json:"confidence"`
}

func (q *Queries) UpsertSystemPatternRule(ctx context.Context, arg UpsertSystemPatternRuleParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, upsertSystemPatternRule,
		arg.HouseholdID,
		arg.Priority,
		arg.Pattern,
		arg.CategoryID,
		arg.Confidence,
	)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
		&i.Confidence,
		&i.IsSystem,
		&i.HouseholdID,
	)
	return i, err
}

const upsertTransactionClassification = `-- name: UpsertTransactionClassification :one
INSERT INTO transaction_classifications (
    transaction_id,
    category_id,
    merchant_id,
    source,
    confidence,
    algorithm_version,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (transaction_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    merchant_id = EXCLUDED.merchant_id,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    algorithm_version = EXCLUDED.algorithm_version,
    updated_at = now()
WHERE transaction_classifications.source <> 'user_rule'
RETURNING transaction_id, category_id, merchant_id, source, confidence, algorithm_version, updated_at
`

type UpsertTransactionClassificationParams struct {
	TransactionID    uuid.UUID   `json:"transaction_id"`
	CategoryID       uuid.UUID   `json:"category_id"`
	MerchantID       pgtype.UUID `json:"merchant_id"`
	Source           string      `json:"source"`
	Confidence       string      `json:"confidence"`
	AlgorithmVersion string      `json:"algorithm_version"`
}

func (q *Queries) UpsertTransactionClassification(ctx context.Context, arg UpsertTransactionClassificationParams) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, upsertTransactionClassification,
		arg.TransactionID,
		arg.CategoryID,
		arg.MerchantID,
		arg.Source,
		arg.Confidence,
		arg.AlgorithmVersion,
	)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}
