// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countClassificationsBySource = `-- name: CountClassificationsBySource :many
SELECT source, COUNT(*)::bigint AS count
FROM transaction_classifications
GROUP BY source
ORDER BY source
`

type CountClassificationsBySourceRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountClassificationsBySource(ctx context.Context) ([]CountClassificationsBySourceRow, error) {
	rows, err := q.db.Query(ctx, countClassificationsBySource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountClassificationsBySourceRow{}
	for rows.Next() {
		var i CountClassificationsBySourceRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createClassificationRule = `-- name: CreateClassificationRule :one
INSERT INTO classification_rules (
    priority,
    merchant_id,
    category_id,
    created_from_transaction_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at
`

type CreateClassificationRuleParams struct {
	Priority                 int32       `json:"priority"`
	MerchantID               pgtype.UUID `json:"merchant_id"`
	CategoryID               uuid.UUID   `json:"category_id"`
	CreatedFromTransactionID pgtype.UUID `json:"created_from_transaction_id"`
}

func (q *Queries) CreateClassificationRule(ctx context.Context, arg CreateClassificationRuleParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, createClassificationRule,
		arg.Priority,
		arg.MerchantID,
		arg.CategoryID,
		arg.CreatedFromTransactionID,
	)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const forceUpsertTransactionClassification = `-- name: ForceUpsertTransactionClassification :one
INSERT INTO transaction_classifications (
    transaction_id,
    category_id,
    merchant_id,
    source,
    confidence,
    algorithm_version,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (transaction_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    merchant_id = EXCLUDED.merchant_id,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    algorithm_version = EXCLUDED.algorithm_version,
    updated_at = now()
RETURNING transaction_id, category_id, merchant_id, source, confidence, algorithm_version, updated_at
`

type ForceUpsertTransactionClassificationParams struct {
	TransactionID    uuid.UUID   `json:"transaction_id"`
	CategoryID       uuid.UUID   `json:"category_id"`
	MerchantID       pgtype.UUID `json:"merchant_id"`
	Source           string      `json:"source"`
	Confidence       string      `json:"confidence"`
	AlgorithmVersion string      `json:"algorithm_version"`
}

func (q *Queries) ForceUpsertTransactionClassification(ctx context.Context, arg ForceUpsertTransactionClassificationParams) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, forceUpsertTransactionClassification,
		arg.TransactionID,
		arg.CategoryID,
		arg.MerchantID,
		arg.Source,
		arg.Confidence,
		arg.AlgorithmVersion,
	)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassificationRuleByMerchant = `-- name: GetClassificationRuleByMerchant :one
SELECT id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at
FROM classification_rules
WHERE merchant_id = $1
`

func (q *Queries) GetClassificationRuleByMerchant(ctx context.Context, merchantID pgtype.UUID) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, getClassificationRuleByMerchant, merchantID)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionClassification = `-- name: GetTransactionClassification :one
SELECT transaction_id, category_id, merchant_id, source, confidence, algorithm_version, updated_at
FROM transaction_classifications
WHERE transaction_id = $1
`

func (q *Queries) GetTransactionClassification(ctx context.Context, transactionID uuid.UUID) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, getTransactionClassification, transactionID)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionForClassify = `-- name: GetTransactionForClassify :one
SELECT
    id,
    counterparty,
    purpose,
    booking_text,
    amount
FROM transactions
WHERE id = $1
`

type GetTransactionForClassifyRow struct {
	ID           uuid.UUID       `json:"id"`
	Counterparty string          `json:"counterparty"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Amount       decimal.Decimal `json:"amount"`
}

func (q *Queries) GetTransactionForClassify(ctx context.Context, id uuid.UUID) (GetTransactionForClassifyRow, error) {
	row := q.db.QueryRow(ctx, getTransactionForClassify, id)
	var i GetTransactionForClassifyRow
	err := row.Scan(
		&i.ID,
		&i.Counterparty,
		&i.Purpose,
		&i.BookingText,
		&i.Amount,
	)
	return i, err
}

const listClassificationQueue = `-- name: ListClassificationQueue :many
SELECT
    t.id AS transaction_id,
    t.booking_date,
    t.amount,
    t.counterparty,
    t.purpose,
    t.booking_text,
    c.slug AS category_slug,
    c.display_name AS category_name,
    tc.source,
    tc.confidence,
    m.id AS merchant_id,
    COALESCE(m.display_name, '') AS merchant_name
FROM transaction_classifications tc
JOIN transactions t ON t.id = tc.transaction_id
JOIN categories c ON c.id = tc.category_id
LEFT JOIN merchants m ON m.id = tc.merchant_id
WHERE tc.source <> 'user_rule'
  AND c.slug <> 'transfer'
  AND (
    tc.source = 'unresolved'
    OR tc.confidence = 'low'
    OR ABS(t.amount) >= 100
  )
ORDER BY ABS(t.amount) DESC, t.booking_date DESC, t.id ASC
LIMIT 50
`

type ListClassificationQueueRow struct {
	TransactionID uuid.UUID       `json:"transaction_id"`
	BookingDate   pgtype.Date     `json:"booking_date"`
	Amount        decimal.Decimal `json:"amount"`
	Counterparty  string          `json:"counterparty"`
	Purpose       string          `json:"purpose"`
	BookingText   string          `json:"booking_text"`
	CategorySlug  string          `json:"category_slug"`
	CategoryName  string          `json:"category_name"`
	Source        string          `json:"source"`
	Confidence    string          `json:"confidence"`
	MerchantID    pgtype.UUID     `json:"merchant_id"`
	MerchantName  string          `json:"merchant_name"`
}

func (q *Queries) ListClassificationQueue(ctx context.Context) ([]ListClassificationQueueRow, error) {
	rows, err := q.db.Query(ctx, listClassificationQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassificationQueueRow{}
	for rows.Next() {
		var i ListClassificationQueueRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.BookingDate,
			&i.Amount,
			&i.Counterparty,
			&i.Purpose,
			&i.BookingText,
			&i.CategorySlug,
			&i.CategoryName,
			&i.Source,
			&i.Confidence,
			&i.MerchantID,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassificationRules = `-- name: ListClassificationRules :many
SELECT id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at
FROM classification_rules
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListClassificationRules(ctx context.Context) ([]ClassificationRule, error) {
	rows, err := q.db.Query(ctx, listClassificationRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassificationRule{}
	for rows.Next() {
		var i ClassificationRule
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.MerchantID,
			&i.Pattern,
			&i.CategoryID,
			&i.CreatedFromTransactionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedTransferTransactionIDs = `-- name: ListConfirmedTransferTransactionIDs :many
SELECT tx_out_id AS transaction_id FROM transfer_pairs WHERE status = 'confirmed'
UNION
SELECT tx_in_id AS transaction_id FROM transfer_pairs WHERE status = 'confirmed'
`

func (q *Queries) ListConfirmedTransferTransactionIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConfirmedTransferTransactionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var transaction_id uuid.UUID
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForClassify = `-- name: ListTransactionsForClassify :many
SELECT
    id,
    counterparty,
    purpose,
    booking_text,
    amount
FROM transactions
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForClassifyRow struct {
	ID           uuid.UUID       `json:"id"`
	Counterparty string          `json:"counterparty"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Amount       decimal.Decimal `json:"amount"`
}

func (q *Queries) ListTransactionsForClassify(ctx context.Context) ([]ListTransactionsForClassifyRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForClassify)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForClassifyRow{}
	for rows.Next() {
		var i ListTransactionsForClassifyRow
		if err := rows.Scan(
			&i.ID,
			&i.Counterparty,
			&i.Purpose,
			&i.BookingText,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassificationRuleCategory = `-- name: UpdateClassificationRuleCategory :one
UPDATE classification_rules
SET
    category_id = $2,
    created_from_transaction_id = $3,
    priority = $4
WHERE id = $1
RETURNING id, priority, merchant_id, pattern, category_id, created_from_transaction_id, created_at
`

type UpdateClassificationRuleCategoryParams struct {
	ID                       uuid.UUID   `json:"id"`
	CategoryID               uuid.UUID   `json:"category_id"`
	CreatedFromTransactionID pgtype.UUID `json:"created_from_transaction_id"`
	Priority                 int32       `json:"priority"`
}

func (q *Queries) UpdateClassificationRuleCategory(ctx context.Context, arg UpdateClassificationRuleCategoryParams) (ClassificationRule, error) {
	row := q.db.QueryRow(ctx, updateClassificationRuleCategory,
		arg.ID,
		arg.CategoryID,
		arg.CreatedFromTransactionID,
		arg.Priority,
	)
	var i ClassificationRule
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.MerchantID,
		&i.Pattern,
		&i.CategoryID,
		&i.CreatedFromTransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const updateMerchantDefaultCategory = `-- name: UpdateMerchantDefaultCategory :one
UPDATE merchants
SET default_category_id = $2
WHERE id = $1
RETURNING id, display_name, default_category_id, created_at
`

type UpdateMerchantDefaultCategoryParams struct {
	ID                uuid.UUID   `json:"id"`
	DefaultCategoryID pgtype.UUID `json:"default_category_id"`
}

func (q *Queries) UpdateMerchantDefaultCategory(ctx context.Context, arg UpdateMerchantDefaultCategoryParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantDefaultCategory, arg.ID, arg.DefaultCategoryID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DefaultCategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTransactionClassification = `-- name: UpsertTransactionClassification :one
INSERT INTO transaction_classifications (
    transaction_id,
    category_id,
    merchant_id,
    source,
    confidence,
    algorithm_version,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (transaction_id) DO UPDATE SET
    category_id = EXCLUDED.category_id,
    merchant_id = EXCLUDED.merchant_id,
    source = EXCLUDED.source,
    confidence = EXCLUDED.confidence,
    algorithm_version = EXCLUDED.algorithm_version,
    updated_at = now()
WHERE transaction_classifications.source <> 'user_rule'
RETURNING transaction_id, category_id, merchant_id, source, confidence, algorithm_version, updated_at
`

type UpsertTransactionClassificationParams struct {
	TransactionID    uuid.UUID   `json:"transaction_id"`
	CategoryID       uuid.UUID   `json:"category_id"`
	MerchantID       pgtype.UUID `json:"merchant_id"`
	Source           string      `json:"source"`
	Confidence       string      `json:"confidence"`
	AlgorithmVersion string      `json:"algorithm_version"`
}

func (q *Queries) UpsertTransactionClassification(ctx context.Context, arg UpsertTransactionClassificationParams) (TransactionClassification, error) {
	row := q.db.QueryRow(ctx, upsertTransactionClassification,
		arg.TransactionID,
		arg.CategoryID,
		arg.MerchantID,
		arg.Source,
		arg.Confidence,
		arg.AlgorithmVersion,
	)
	var i TransactionClassification
	err := row.Scan(
		&i.TransactionID,
		&i.CategoryID,
		&i.MerchantID,
		&i.Source,
		&i.Confidence,
		&i.AlgorithmVersion,
		&i.UpdatedAt,
	)
	return i, err
}
