// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getAction = `-- name: GetAction :one
SELECT id, decision_id, title, expected_annual_effect, due_on, status, outcome_note, verified_at, created_at, updated_at
FROM actions
WHERE id = $1
`

func (q *Queries) GetAction(ctx context.Context, id uuid.UUID) (Action, error) {
	row := q.db.QueryRow(ctx, getAction, id)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Title,
		&i.ExpectedAnnualEffect,
		&i.DueOn,
		&i.Status,
		&i.OutcomeNote,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDecision = `-- name: GetDecision :one
SELECT id, review_id, scenario_id, title, assumptions, target_value, decided_at, created_at
FROM decisions
WHERE id = $1
`

func (q *Queries) GetDecision(ctx context.Context, id uuid.UUID) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecision, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ScenarioID,
		&i.Title,
		&i.Assumptions,
		&i.TargetValue,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAction = `-- name: InsertAction :one
INSERT INTO actions (
    decision_id,
    title,
    expected_annual_effect,
    due_on,
    status,
    outcome_note
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, decision_id, title, expected_annual_effect, due_on, status, outcome_note, verified_at, created_at, updated_at
`

type InsertActionParams struct {
	DecisionID           uuid.UUID       `json:"decision_id"`
	Title                string          `json:"title"`
	ExpectedAnnualEffect decimal.Decimal `json:"expected_annual_effect"`
	DueOn                pgtype.Date     `json:"due_on"`
	Status               string          `json:"status"`
	OutcomeNote          string          `json:"outcome_note"`
}

func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (Action, error) {
	row := q.db.QueryRow(ctx, insertAction,
		arg.DecisionID,
		arg.Title,
		arg.ExpectedAnnualEffect,
		arg.DueOn,
		arg.Status,
		arg.OutcomeNote,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Title,
		&i.ExpectedAnnualEffect,
		&i.DueOn,
		&i.Status,
		&i.OutcomeNote,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDecision = `-- name: InsertDecision :one
INSERT INTO decisions (
    review_id,
    scenario_id,
    title,
    assumptions,
    target_value
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, review_id, scenario_id, title, assumptions, target_value, decided_at, created_at
`

type InsertDecisionParams struct {
	ReviewID    pgtype.UUID    `json:"review_id"`
	ScenarioID  pgtype.UUID    `json:"scenario_id"`
	Title       string         `json:"title"`
	Assumptions []byte         `json:"assumptions"`
	TargetValue pgtype.Numeric `json:"target_value"`
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, insertDecision,
		arg.ReviewID,
		arg.ScenarioID,
		arg.Title,
		arg.Assumptions,
		arg.TargetValue,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ScenarioID,
		&i.Title,
		&i.Assumptions,
		&i.TargetValue,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActions = `-- name: ListActions :many
SELECT id, decision_id, title, expected_annual_effect, due_on, status, outcome_note, verified_at, created_at, updated_at
FROM actions
WHERE ($1::text IS NULL OR status = $1)
ORDER BY due_on ASC, created_at DESC
LIMIT $2
`

type ListActionsParams struct {
	Status   pgtype.Text `json:"status"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListActions(ctx context.Context, arg ListActionsParams) ([]Action, error) {
	rows, err := q.db.Query(ctx, listActions, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Action{}
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Title,
			&i.ExpectedAnnualEffect,
			&i.DueOn,
			&i.Status,
			&i.OutcomeNote,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsForDecision = `-- name: ListActionsForDecision :many
SELECT id, decision_id, title, expected_annual_effect, due_on, status, outcome_note, verified_at, created_at, updated_at
FROM actions
WHERE decision_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListActionsForDecision(ctx context.Context, decisionID uuid.UUID) ([]Action, error) {
	rows, err := q.db.Query(ctx, listActionsForDecision, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Action{}
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Title,
			&i.ExpectedAnnualEffect,
			&i.DueOn,
			&i.Status,
			&i.OutcomeNote,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, review_id, scenario_id, title, assumptions, target_value, decided_at, created_at
FROM decisions
ORDER BY decided_at DESC
LIMIT $1
`

func (q *Queries) ListDecisions(ctx context.Context, rowLimit int32) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisions, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ScenarioID,
			&i.Title,
			&i.Assumptions,
			&i.TargetValue,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionStatus = `-- name: UpdateActionStatus :one
UPDATE actions
SET
    status = $2,
    outcome_note = $3,
    verified_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, decision_id, title, expected_annual_effect, due_on, status, outcome_note, verified_at, created_at, updated_at
`

type UpdateActionStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	OutcomeNote string             `json:"outcome_note"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) (Action, error) {
	row := q.db.QueryRow(ctx, updateActionStatus,
		arg.ID,
		arg.Status,
		arg.OutcomeNote,
		arg.VerifiedAt,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Title,
		&i.ExpectedAnnualEffect,
		&i.DueOn,
		&i.Status,
		&i.OutcomeNote,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
