// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getAction = `-- name: GetAction :one
SELECT a.id, a.decision_id, a.title, a.expected_annual_effect, a.due_on, a.status, a.outcome_note, a.verified_at, a.created_at, a.updated_at
FROM actions a
JOIN decisions d ON d.id = a.decision_id
WHERE a.id = $1 AND d.household_id = $2
`

type GetActionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetAction(ctx context.Context, arg GetActionParams) (Action, error) {
	row := q.db.QueryRow(ctx, getAction, arg.ID, arg.HouseholdID)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Title,
		&i.ExpectedAnnualEffect,
		&i.DueOn,
		&i.Status,
		&i.OutcomeNote,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDecision = `-- name: GetDecision :one
SELECT id, review_id, scenario_id, title, assumptions, target_value, decided_at, created_at, household_id
FROM decisions
WHERE id = $1 AND household_id = $2
`

type GetDecisionParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetDecision(ctx context.Context, arg GetDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecision, arg.ID, arg.HouseholdID)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ScenarioID,
		&i.Title,
		&i.Assumptions,
		&i.TargetValue,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const insertAction = `-- name: InsertAction :one
INSERT INTO actions (
    decision_id,
    title,
    expected_annual_effect,
    due_on,
    status,
    outcome_note
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, decision_id, title, expected_annual_effect, due_on, status, outcome_note, verified_at, created_at, updated_at
`

type InsertActionParams struct {
	DecisionID           uuid.UUID       `json:"decision_id"`
	Title                string          `json:"title"`
	ExpectedAnnualEffect decimal.Decimal `json:"expected_annual_effect"`
	DueOn                pgtype.Date     `json:"due_on"`
	Status               string          `json:"status"`
	OutcomeNote          string          `json:"outcome_note"`
}

func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (Action, error) {
	row := q.db.QueryRow(ctx, insertAction,
		arg.DecisionID,
		arg.Title,
		arg.ExpectedAnnualEffect,
		arg.DueOn,
		arg.Status,
		arg.OutcomeNote,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Title,
		&i.ExpectedAnnualEffect,
		&i.DueOn,
		&i.Status,
		&i.OutcomeNote,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDecision = `-- name: InsertDecision :one
INSERT INTO decisions (
    household_id,
    review_id,
    scenario_id,
    title,
    assumptions,
    target_value
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, review_id, scenario_id, title, assumptions, target_value, decided_at, created_at, household_id
`

type InsertDecisionParams struct {
	HouseholdID uuid.UUID      `json:"household_id"`
	ReviewID    pgtype.UUID    `json:"review_id"`
	ScenarioID  pgtype.UUID    `json:"scenario_id"`
	Title       string         `json:"title"`
	Assumptions []byte         `json:"assumptions"`
	TargetValue pgtype.Numeric `json:"target_value"`
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, insertDecision,
		arg.HouseholdID,
		arg.ReviewID,
		arg.ScenarioID,
		arg.Title,
		arg.Assumptions,
		arg.TargetValue,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.ScenarioID,
		&i.Title,
		&i.Assumptions,
		&i.TargetValue,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const listActions = `-- name: ListActions :many
SELECT a.id, a.decision_id, a.title, a.expected_annual_effect, a.due_on, a.status, a.outcome_note, a.verified_at, a.created_at, a.updated_at
FROM actions a
JOIN decisions d ON d.id = a.decision_id
WHERE d.household_id = $1
  AND ($2::text IS NULL OR a.status = $2)
ORDER BY a.due_on ASC, a.created_at DESC
LIMIT $3
`

type ListActionsParams struct {
	HouseholdID uuid.UUID   `json:"household_id"`
	Status      pgtype.Text `json:"status"`
	RowLimit    int32       `json:"row_limit"`
}

func (q *Queries) ListActions(ctx context.Context, arg ListActionsParams) ([]Action, error) {
	rows, err := q.db.Query(ctx, listActions, arg.HouseholdID, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Action{}
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Title,
			&i.ExpectedAnnualEffect,
			&i.DueOn,
			&i.Status,
			&i.OutcomeNote,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsForDecision = `-- name: ListActionsForDecision :many
SELECT a.id, a.decision_id, a.title, a.expected_annual_effect, a.due_on, a.status, a.outcome_note, a.verified_at, a.created_at, a.updated_at
FROM actions a
JOIN decisions d ON d.id = a.decision_id
WHERE a.decision_id = $1 AND d.household_id = $2
ORDER BY a.created_at ASC
`

type ListActionsForDecisionParams struct {
	DecisionID  uuid.UUID `json:"decision_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListActionsForDecision(ctx context.Context, arg ListActionsForDecisionParams) ([]Action, error) {
	rows, err := q.db.Query(ctx, listActionsForDecision, arg.DecisionID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Action{}
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.Title,
			&i.ExpectedAnnualEffect,
			&i.DueOn,
			&i.Status,
			&i.OutcomeNote,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, review_id, scenario_id, title, assumptions, target_value, decided_at, created_at, household_id
FROM decisions
WHERE household_id = $1
ORDER BY decided_at DESC
LIMIT $2
`

type ListDecisionsParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	RowLimit    int32     `json:"row_limit"`
}

func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisions, arg.HouseholdID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.ScenarioID,
			&i.Title,
			&i.Assumptions,
			&i.TargetValue,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionStatus = `-- name: UpdateActionStatus :one
UPDATE actions a
SET
    status = $3,
    outcome_note = $4,
    verified_at = $5,
    updated_at = now()
FROM decisions d
WHERE a.id = $1
  AND d.id = a.decision_id
  AND d.household_id = $2
RETURNING a.id, a.decision_id, a.title, a.expected_annual_effect, a.due_on, a.status, a.outcome_note, a.verified_at, a.created_at, a.updated_at
`

type UpdateActionStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	Status      string             `json:"status"`
	OutcomeNote string             `json:"outcome_note"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) UpdateActionStatus(ctx context.Context, arg UpdateActionStatusParams) (Action, error) {
	row := q.db.QueryRow(ctx, updateActionStatus,
		arg.ID,
		arg.HouseholdID,
		arg.Status,
		arg.OutcomeNote,
		arg.VerifiedAt,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.Title,
		&i.ExpectedAnnualEffect,
		&i.DueOn,
		&i.Status,
		&i.OutcomeNote,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
