// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forecasts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getForecast = `-- name: GetForecast :one
SELECT id, baseline_id, horizon_days, starting_balance, assumptions, series, min_balance, ending_balance, algorithm_version, created_at, household_id
FROM forecasts
WHERE id = $1 AND household_id = $2
`

type GetForecastParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetForecast(ctx context.Context, arg GetForecastParams) (Forecast, error) {
	row := q.db.QueryRow(ctx, getForecast, arg.ID, arg.HouseholdID)
	var i Forecast
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.HorizonDays,
		&i.StartingBalance,
		&i.Assumptions,
		&i.Series,
		&i.MinBalance,
		&i.EndingBalance,
		&i.AlgorithmVersion,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const getLatestForecastForBaseline = `-- name: GetLatestForecastForBaseline :one
SELECT id, baseline_id, horizon_days, starting_balance, assumptions, series, min_balance, ending_balance, algorithm_version, created_at, household_id
FROM forecasts
WHERE baseline_id = $1 AND household_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestForecastForBaselineParams struct {
	BaselineID  uuid.UUID `json:"baseline_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetLatestForecastForBaseline(ctx context.Context, arg GetLatestForecastForBaselineParams) (Forecast, error) {
	row := q.db.QueryRow(ctx, getLatestForecastForBaseline, arg.BaselineID, arg.HouseholdID)
	var i Forecast
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.HorizonDays,
		&i.StartingBalance,
		&i.Assumptions,
		&i.Series,
		&i.MinBalance,
		&i.EndingBalance,
		&i.AlgorithmVersion,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, forecast_id, kind, params, result, status, created_at, household_id
FROM scenarios
WHERE id = $1 AND household_id = $2
`

type GetScenarioParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetScenario(ctx context.Context, arg GetScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, getScenario, arg.ID, arg.HouseholdID)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.ForecastID,
		&i.Kind,
		&i.Params,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const insertForecast = `-- name: InsertForecast :one
INSERT INTO forecasts (
    household_id,
    baseline_id,
    horizon_days,
    starting_balance,
    assumptions,
    series,
    min_balance,
    ending_balance,
    algorithm_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, baseline_id, horizon_days, starting_balance, assumptions, series, min_balance, ending_balance, algorithm_version, created_at, household_id
`

type InsertForecastParams struct {
	HouseholdID      uuid.UUID       `json:"household_id"`
	BaselineID       uuid.UUID       `json:"baseline_id"`
	HorizonDays      int32           `json:"horizon_days"`
	StartingBalance  decimal.Decimal `json:"starting_balance"`
	Assumptions      []byte          `json:"assumptions"`
	Series           []byte          `json:"series"`
	MinBalance       decimal.Decimal `json:"min_balance"`
	EndingBalance    decimal.Decimal `json:"ending_balance"`
	AlgorithmVersion string          `json:"algorithm_version"`
}

func (q *Queries) InsertForecast(ctx context.Context, arg InsertForecastParams) (Forecast, error) {
	row := q.db.QueryRow(ctx, insertForecast,
		arg.HouseholdID,
		arg.BaselineID,
		arg.HorizonDays,
		arg.StartingBalance,
		arg.Assumptions,
		arg.Series,
		arg.MinBalance,
		arg.EndingBalance,
		arg.AlgorithmVersion,
	)
	var i Forecast
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.HorizonDays,
		&i.StartingBalance,
		&i.Assumptions,
		&i.Series,
		&i.MinBalance,
		&i.EndingBalance,
		&i.AlgorithmVersion,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const insertScenario = `-- name: InsertScenario :one
INSERT INTO scenarios (
    household_id,
    forecast_id,
    kind,
    params,
    result,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, forecast_id, kind, params, result, status, created_at, household_id
`

type InsertScenarioParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	ForecastID  uuid.UUID `json:"forecast_id"`
	Kind        string    `json:"kind"`
	Params      []byte    `json:"params"`
	Result      []byte    `json:"result"`
	Status      string    `json:"status"`
}

func (q *Queries) InsertScenario(ctx context.Context, arg InsertScenarioParams) (Scenario, error) {
	row := q.db.QueryRow(ctx, insertScenario,
		arg.HouseholdID,
		arg.ForecastID,
		arg.Kind,
		arg.Params,
		arg.Result,
		arg.Status,
	)
	var i Scenario
	err := row.Scan(
		&i.ID,
		&i.ForecastID,
		&i.Kind,
		&i.Params,
		&i.Result,
		&i.Status,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const listScenariosForForecast = `-- name: ListScenariosForForecast :many
SELECT id, forecast_id, kind, params, result, status, created_at, household_id
FROM scenarios
WHERE forecast_id = $1 AND household_id = $2
ORDER BY created_at DESC
`

type ListScenariosForForecastParams struct {
	ForecastID  uuid.UUID `json:"forecast_id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ListScenariosForForecast(ctx context.Context, arg ListScenariosForForecastParams) ([]Scenario, error) {
	rows, err := q.db.Query(ctx, listScenariosForForecast, arg.ForecastID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scenario{}
	for rows.Next() {
		var i Scenario
		if err := rows.Scan(
			&i.ID,
			&i.ForecastID,
			&i.Kind,
			&i.Params,
			&i.Result,
			&i.Status,
			&i.CreatedAt,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
