// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMerchantAliases = `-- name: CountMerchantAliases :one
SELECT COUNT(*)::bigint AS count FROM merchant_aliases
`

func (q *Queries) CountMerchantAliases(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchantAliases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (display_name, default_category_id)
VALUES ($1, $2)
RETURNING id, display_name, default_category_id, created_at
`

type CreateMerchantParams struct {
	DisplayName       string      `json:"display_name"`
	DefaultCategoryID pgtype.UUID `json:"default_category_id"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, arg.DisplayName, arg.DefaultCategoryID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DefaultCategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const createMerchantAlias = `-- name: CreateMerchantAlias :one
INSERT INTO merchant_aliases (merchant_id, match_type, pattern)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, match_type, pattern, created_at
`

type CreateMerchantAliasParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	MatchType  string    `json:"match_type"`
	Pattern    string    `json:"pattern"`
}

func (q *Queries) CreateMerchantAlias(ctx context.Context, arg CreateMerchantAliasParams) (MerchantAlias, error) {
	row := q.db.QueryRow(ctx, createMerchantAlias, arg.MerchantID, arg.MatchType, arg.Pattern)
	var i MerchantAlias
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.MatchType,
		&i.Pattern,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantAlias = `-- name: GetMerchantAlias :one
SELECT id, merchant_id, match_type, pattern, created_at
FROM merchant_aliases
WHERE match_type = $1 AND pattern = $2
`

type GetMerchantAliasParams struct {
	MatchType string `json:"match_type"`
	Pattern   string `json:"pattern"`
}

func (q *Queries) GetMerchantAlias(ctx context.Context, arg GetMerchantAliasParams) (MerchantAlias, error) {
	row := q.db.QueryRow(ctx, getMerchantAlias, arg.MatchType, arg.Pattern)
	var i MerchantAlias
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.MatchType,
		&i.Pattern,
		&i.CreatedAt,
	)
	return i, err
}

const listMerchantSourceLabels = `-- name: ListMerchantSourceLabels :many
SELECT DISTINCT
    counterparty,
    purpose
FROM transactions
WHERE counterparty <> '' OR purpose <> ''
ORDER BY counterparty, purpose
`

type ListMerchantSourceLabelsRow struct {
	Counterparty string `json:"counterparty"`
	Purpose      string `json:"purpose"`
}

func (q *Queries) ListMerchantSourceLabels(ctx context.Context) ([]ListMerchantSourceLabelsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantSourceLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantSourceLabelsRow{}
	for rows.Next() {
		var i ListMerchantSourceLabelsRow
		if err := rows.Scan(&i.Counterparty, &i.Purpose); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchants = `-- name: ListMerchants :many
SELECT
    m.id,
    m.display_name,
    m.default_category_id,
    m.created_at,
    COUNT(a.id)::bigint AS alias_count
FROM merchants m
LEFT JOIN merchant_aliases a ON a.merchant_id = m.id
GROUP BY m.id
ORDER BY m.display_name ASC
`

type ListMerchantsRow struct {
	ID                uuid.UUID          `json:"id"`
	DisplayName       string             `json:"display_name"`
	DefaultCategoryID pgtype.UUID        `json:"default_category_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AliasCount        int64              `json:"alias_count"`
}

func (q *Queries) ListMerchants(ctx context.Context) ([]ListMerchantsRow, error) {
	rows, err := q.db.Query(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsRow{}
	for rows.Next() {
		var i ListMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.DefaultCategoryID,
			&i.CreatedAt,
			&i.AliasCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
