// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID               uuid.UUID          `json:"id"`
	DisplayName      string             `json:"display_name"`
	Bank             string             `json:"bank"`
	Currency         string             `json:"currency"`
	OrderAccount     pgtype.Text        `json:"order_account"`
	MaskedIdentifier string             `json:"masked_identifier"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Action struct {
	ID                   uuid.UUID          `json:"id"`
	DecisionID           uuid.UUID          `json:"decision_id"`
	Title                string             `json:"title"`
	ExpectedAnnualEffect decimal.Decimal    `json:"expected_annual_effect"`
	DueOn                pgtype.Date        `json:"due_on"`
	Status               string             `json:"status"`
	OutcomeNote          string             `json:"outcome_note"`
	VerifiedAt           pgtype.Timestamptz `json:"verified_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type BaselineAdjustment struct {
	ID            uuid.UUID          `json:"id"`
	BaselineID    uuid.UUID          `json:"baseline_id"`
	MetricKey     string             `json:"metric_key"`
	PreviousValue decimal.Decimal    `json:"previous_value"`
	NewValue      decimal.Decimal    `json:"new_value"`
	Reason        string             `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Kind        string             `json:"kind"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ClassificationRule struct {
	ID                       uuid.UUID          `json:"id"`
	Priority                 int32              `json:"priority"`
	MerchantID               pgtype.UUID        `json:"merchant_id"`
	Pattern                  pgtype.Text        `json:"pattern"`
	CategoryID               uuid.UUID          `json:"category_id"`
	CreatedFromTransactionID pgtype.UUID        `json:"created_from_transaction_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type Decision struct {
	ID          uuid.UUID          `json:"id"`
	ReviewID    pgtype.UUID        `json:"review_id"`
	ScenarioID  pgtype.UUID        `json:"scenario_id"`
	Title       string             `json:"title"`
	Assumptions []byte             `json:"assumptions"`
	TargetValue pgtype.Numeric     `json:"target_value"`
	DecidedAt   pgtype.Timestamptz `json:"decided_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type FinancialBaseline struct {
	ID                      uuid.UUID          `json:"id"`
	PeriodFrom              pgtype.Date        `json:"period_from"`
	PeriodTo                pgtype.Date        `json:"period_to"`
	AlgorithmVersion        string             `json:"algorithm_version"`
	Status                  string             `json:"status"`
	RegularMonthlyIncome    decimal.Decimal    `json:"regular_monthly_income"`
	MonthlyFixedCosts       decimal.Decimal    `json:"monthly_fixed_costs"`
	MonthlyIrregularCosts   decimal.Decimal    `json:"monthly_irregular_costs"`
	AvgVariableSpend        decimal.Decimal    `json:"avg_variable_spend"`
	SustainableFreeCashflow decimal.Decimal    `json:"sustainable_free_cashflow"`
	Confidence              string             `json:"confidence"`
	Assumptions             []byte             `json:"assumptions"`
	Evidence                []byte             `json:"evidence"`
	ConfirmedAt             pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Forecast struct {
	ID               uuid.UUID          `json:"id"`
	BaselineID       uuid.UUID          `json:"baseline_id"`
	HorizonDays      int32              `json:"horizon_days"`
	StartingBalance  decimal.Decimal    `json:"starting_balance"`
	Assumptions      []byte             `json:"assumptions"`
	Series           []byte             `json:"series"`
	MinBalance       decimal.Decimal    `json:"min_balance"`
	EndingBalance    decimal.Decimal    `json:"ending_balance"`
	AlgorithmVersion string             `json:"algorithm_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ImportRun struct {
	ID             uuid.UUID          `json:"id"`
	AccountID      uuid.UUID          `json:"account_id"`
	SourceFilename string             `json:"source_filename"`
	FileHash       string             `json:"file_hash"`
	ParserName     string             `json:"parser_name"`
	ParserVersion  string             `json:"parser_version"`
	Status         string             `json:"status"`
	PeriodFrom     pgtype.Date        `json:"period_from"`
	PeriodTo       pgtype.Date        `json:"period_to"`
	RowTotal       int32              `json:"row_total"`
	RowValid       int32              `json:"row_valid"`
	RowInvalid     int32              `json:"row_invalid"`
	RowInserted    int32              `json:"row_inserted"`
	RowDuplicate   int32              `json:"row_duplicate"`
	Warnings       []byte             `json:"warnings"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CommittedAt    pgtype.Timestamptz `json:"committed_at"`
	RolledBackAt   pgtype.Timestamptz `json:"rolled_back_at"`
}

type Merchant struct {
	ID                uuid.UUID          `json:"id"`
	DisplayName       string             `json:"display_name"`
	DefaultCategoryID pgtype.UUID        `json:"default_category_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MerchantAlias struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	MatchType  string             `json:"match_type"`
	Pattern    string             `json:"pattern"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type MoneyReview struct {
	ID            uuid.UUID          `json:"id"`
	BaselineID    uuid.UUID          `json:"baseline_id"`
	PeriodFrom    pgtype.Date        `json:"period_from"`
	PeriodTo      pgtype.Date        `json:"period_to"`
	Status        string             `json:"status"`
	Summary       string             `json:"summary"`
	Findings      []byte             `json:"findings"`
	DataFreshness string             `json:"data_freshness"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RecurringSeries struct {
	ID            uuid.UUID          `json:"id"`
	Fingerprint   string             `json:"fingerprint"`
	DisplayName   string             `json:"display_name"`
	Cadence       string             `json:"cadence"`
	Kind          string             `json:"kind"`
	Status        string             `json:"status"`
	AmountTypical decimal.Decimal    `json:"amount_typical"`
	AmountLast    decimal.Decimal    `json:"amount_last"`
	AmountChanged bool               `json:"amount_changed"`
	NextExpected  pgtype.Date        `json:"next_expected"`
	Uncertainty   string             `json:"uncertainty"`
	MemberCount   int32              `json:"member_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RecurringSeriesMember struct {
	SeriesID      uuid.UUID       `json:"series_id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	BookingDate   pgtype.Date     `json:"booking_date"`
	Amount        decimal.Decimal `json:"amount"`
}

type Scenario struct {
	ID         uuid.UUID          `json:"id"`
	ForecastID uuid.UUID          `json:"forecast_id"`
	Kind       string             `json:"kind"`
	Params     []byte             `json:"params"`
	Result     []byte             `json:"result"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                             uuid.UUID       `json:"id"`
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
	AccountID                      pgtype.UUID     `json:"account_id"`
	ImportRunID                    pgtype.UUID     `json:"import_run_id"`
}

type TransactionClassification struct {
	TransactionID    uuid.UUID          `json:"transaction_id"`
	CategoryID       uuid.UUID          `json:"category_id"`
	MerchantID       pgtype.UUID        `json:"merchant_id"`
	Source           string             `json:"source"`
	Confidence       string             `json:"confidence"`
	AlgorithmVersion string             `json:"algorithm_version"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TransferPair struct {
	ID          uuid.UUID          `json:"id"`
	TxOutID     uuid.UUID          `json:"tx_out_id"`
	TxInID      uuid.UUID          `json:"tx_in_id"`
	Status      string             `json:"status"`
	Confidence  string             `json:"confidence"`
	Rationale   []byte             `json:"rationale"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
