// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountTransactions(ctx context.Context) (int64, error)
	CountTransactionsFiltered(ctx context.Context, arg CountTransactionsFilteredParams) (int64, error)
	GetCashflow(ctx context.Context, arg GetCashflowParams) (GetCashflowRow, error)
	GetTopCounterparties(ctx context.Context, arg GetTopCounterpartiesParams) ([]GetTopCounterpartiesRow, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (uuid.UUID, error)
	InsertTransactionIfNew(ctx context.Context, arg InsertTransactionIfNewParams) (uuid.UUID, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
