// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConfirmTransferPair(ctx context.Context, id uuid.UUID) (TransferPair, error)
	CountTransactions(ctx context.Context) (int64, error)
	CountTransactionsByImportRun(ctx context.Context, importRunID pgtype.UUID) (int64, error)
	CountTransactionsFiltered(ctx context.Context, arg CountTransactionsFilteredParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error)
	DeleteTransactionsByImportRun(ctx context.Context, importRunID pgtype.UUID) (int64, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByOrderAccount(ctx context.Context, orderAccount pgtype.Text) (Account, error)
	GetCashflow(ctx context.Context, arg GetCashflowParams) (GetCashflowRow, error)
	GetCashflowV2(ctx context.Context, arg GetCashflowV2Params) (GetCashflowV2Row, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetImportRun(ctx context.Context, id uuid.UUID) (ImportRun, error)
	GetTopCounterparties(ctx context.Context, arg GetTopCounterpartiesParams) ([]GetTopCounterpartiesRow, error)
	GetTransferPair(ctx context.Context, id uuid.UUID) (TransferPair, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (uuid.UUID, error)
	InsertTransactionIfNew(ctx context.Context, arg InsertTransactionIfNewParams) (uuid.UUID, error)
	InsertTransferPair(ctx context.Context, arg InsertTransferPairParams) (TransferPair, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListImportRuns(ctx context.Context, limit int32) ([]ImportRun, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	ListTransactionsForTransferScan(ctx context.Context) ([]ListTransactionsForTransferScanRow, error)
	ListTransferPairLegs(ctx context.Context) ([]ListTransferPairLegsRow, error)
	ListTransferPairs(ctx context.Context) ([]TransferPair, error)
	MarkImportRunRolledBack(ctx context.Context, id uuid.UUID) (ImportRun, error)
	Ping(ctx context.Context) (int32, error)
	RejectTransferPair(ctx context.Context, id uuid.UUID) (TransferPair, error)
	UpdateImportRunCounts(ctx context.Context, arg UpdateImportRunCountsParams) (ImportRun, error)
}

var _ Querier = (*Queries)(nil)
