// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const confirmRecurringSeries = `-- name: ConfirmRecurringSeries :one
UPDATE recurring_series
SET
    status = 'active',
    updated_at = now()
WHERE id = $1
  AND household_id = $2
  AND status = 'uncertain'
RETURNING id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at, household_id
`

type ConfirmRecurringSeriesParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ConfirmRecurringSeries(ctx context.Context, arg ConfirmRecurringSeriesParams) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, confirmRecurringSeries, arg.ID, arg.HouseholdID)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const getRecurringSeries = `-- name: GetRecurringSeries :one
SELECT id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at, household_id
FROM recurring_series
WHERE id = $1 AND household_id = $2
`

type GetRecurringSeriesParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetRecurringSeries(ctx context.Context, arg GetRecurringSeriesParams) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, getRecurringSeries, arg.ID, arg.HouseholdID)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const insertRecurringSeries = `-- name: InsertRecurringSeries :one
INSERT INTO recurring_series (
    household_id,
    fingerprint,
    display_name,
    cadence,
    kind,
    status,
    amount_typical,
    amount_last,
    amount_changed,
    next_expected,
    uncertainty,
    member_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (fingerprint) DO NOTHING
RETURNING id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at, household_id
`

type InsertRecurringSeriesParams struct {
	HouseholdID   uuid.UUID       `json:"household_id"`
	Fingerprint   string          `json:"fingerprint"`
	DisplayName   string          `json:"display_name"`
	Cadence       string          `json:"cadence"`
	Kind          string          `json:"kind"`
	Status        string          `json:"status"`
	AmountTypical decimal.Decimal `json:"amount_typical"`
	AmountLast    decimal.Decimal `json:"amount_last"`
	AmountChanged bool            `json:"amount_changed"`
	NextExpected  pgtype.Date     `json:"next_expected"`
	Uncertainty   string          `json:"uncertainty"`
	MemberCount   int32           `json:"member_count"`
}

func (q *Queries) InsertRecurringSeries(ctx context.Context, arg InsertRecurringSeriesParams) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, insertRecurringSeries,
		arg.HouseholdID,
		arg.Fingerprint,
		arg.DisplayName,
		arg.Cadence,
		arg.Kind,
		arg.Status,
		arg.AmountTypical,
		arg.AmountLast,
		arg.AmountChanged,
		arg.NextExpected,
		arg.Uncertainty,
		arg.MemberCount,
	)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const insertRecurringSeriesMember = `-- name: InsertRecurringSeriesMember :exec
INSERT INTO recurring_series_members (
    series_id,
    transaction_id,
    booking_date,
    amount
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (transaction_id) DO NOTHING
`

type InsertRecurringSeriesMemberParams struct {
	SeriesID      uuid.UUID       `json:"series_id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	BookingDate   pgtype.Date     `json:"booking_date"`
	Amount        decimal.Decimal `json:"amount"`
}

func (q *Queries) InsertRecurringSeriesMember(ctx context.Context, arg InsertRecurringSeriesMemberParams) error {
	_, err := q.db.Exec(ctx, insertRecurringSeriesMember,
		arg.SeriesID,
		arg.TransactionID,
		arg.BookingDate,
		arg.Amount,
	)
	return err
}

const listRecurringMemberTransactionIDs = `-- name: ListRecurringMemberTransactionIDs :many
SELECT m.transaction_id
FROM recurring_series_members m
JOIN recurring_series s ON s.id = m.series_id
WHERE s.household_id = $1
`

func (q *Queries) ListRecurringMemberTransactionIDs(ctx context.Context, householdID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRecurringMemberTransactionIDs, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var transaction_id uuid.UUID
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringSeries = `-- name: ListRecurringSeries :many
SELECT id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at, household_id
FROM recurring_series
WHERE household_id = $1
ORDER BY display_name ASC, created_at DESC
`

func (q *Queries) ListRecurringSeries(ctx context.Context, householdID uuid.UUID) ([]RecurringSeries, error) {
	rows, err := q.db.Query(ctx, listRecurringSeries, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringSeries{}
	for rows.Next() {
		var i RecurringSeries
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.DisplayName,
			&i.Cadence,
			&i.Kind,
			&i.Status,
			&i.AmountTypical,
			&i.AmountLast,
			&i.AmountChanged,
			&i.NextExpected,
			&i.Uncertainty,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringSeriesMembers = `-- name: ListRecurringSeriesMembers :many
SELECT
    m.transaction_id,
    m.booking_date,
    m.amount,
    t.counterparty,
    t.purpose
FROM recurring_series_members m
JOIN transactions t ON t.id = m.transaction_id
JOIN recurring_series s ON s.id = m.series_id
WHERE m.series_id = $1
  AND s.household_id = $2
ORDER BY m.booking_date DESC, m.transaction_id DESC
LIMIT $3
`

type ListRecurringSeriesMembersParams struct {
	SeriesID    uuid.UUID `json:"series_id"`
	HouseholdID uuid.UUID `json:"household_id"`
	RowLimit    int32     `json:"row_limit"`
}

type ListRecurringSeriesMembersRow struct {
	TransactionID uuid.UUID       `json:"transaction_id"`
	BookingDate   pgtype.Date     `json:"booking_date"`
	Amount        decimal.Decimal `json:"amount"`
	Counterparty  string          `json:"counterparty"`
	Purpose       string          `json:"purpose"`
}

func (q *Queries) ListRecurringSeriesMembers(ctx context.Context, arg ListRecurringSeriesMembersParams) ([]ListRecurringSeriesMembersRow, error) {
	rows, err := q.db.Query(ctx, listRecurringSeriesMembers, arg.SeriesID, arg.HouseholdID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringSeriesMembersRow{}
	for rows.Next() {
		var i ListRecurringSeriesMembersRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.BookingDate,
			&i.Amount,
			&i.Counterparty,
			&i.Purpose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForRecurringScan = `-- name: ListTransactionsForRecurringScan :many
SELECT
    id,
    account_id,
    booking_date,
    amount,
    purpose,
    booking_text,
    counterparty
FROM transactions
WHERE household_id = $1
  AND account_id IS NOT NULL
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForRecurringScanRow struct {
	ID           uuid.UUID       `json:"id"`
	AccountID    pgtype.UUID     `json:"account_id"`
	BookingDate  pgtype.Date     `json:"booking_date"`
	Amount       decimal.Decimal `json:"amount"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Counterparty string          `json:"counterparty"`
}

func (q *Queries) ListTransactionsForRecurringScan(ctx context.Context, householdID uuid.UUID) ([]ListTransactionsForRecurringScanRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForRecurringScan, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForRecurringScanRow{}
	for rows.Next() {
		var i ListTransactionsForRecurringScanRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BookingDate,
			&i.Amount,
			&i.Purpose,
			&i.BookingText,
			&i.Counterparty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncertainRecurringSeries = `-- name: ListUncertainRecurringSeries :many
SELECT id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at, household_id
FROM recurring_series
WHERE household_id = $1
  AND status = 'uncertain'
ORDER BY amount_typical DESC, display_name ASC
`

func (q *Queries) ListUncertainRecurringSeries(ctx context.Context, householdID uuid.UUID) ([]RecurringSeries, error) {
	rows, err := q.db.Query(ctx, listUncertainRecurringSeries, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringSeries{}
	for rows.Next() {
		var i RecurringSeries
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.DisplayName,
			&i.Cadence,
			&i.Kind,
			&i.Status,
			&i.AmountTypical,
			&i.AmountLast,
			&i.AmountChanged,
			&i.NextExpected,
			&i.Uncertainty,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRecurringSeries = `-- name: RejectRecurringSeries :one
UPDATE recurring_series
SET
    status = 'ended',
    updated_at = now()
WHERE id = $1
  AND household_id = $2
  AND status = 'uncertain'
RETURNING id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at, household_id
`

type RejectRecurringSeriesParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) RejectRecurringSeries(ctx context.Context, arg RejectRecurringSeriesParams) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, rejectRecurringSeries, arg.ID, arg.HouseholdID)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HouseholdID,
	)
	return i, err
}
