// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const confirmRecurringSeries = `-- name: ConfirmRecurringSeries :one
UPDATE recurring_series
SET
    status = 'active',
    updated_at = now()
WHERE id = $1
  AND status = 'uncertain'
RETURNING id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at
`

func (q *Queries) ConfirmRecurringSeries(ctx context.Context, id uuid.UUID) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, confirmRecurringSeries, id)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecurringSeries = `-- name: GetRecurringSeries :one
SELECT id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at
FROM recurring_series
WHERE id = $1
`

func (q *Queries) GetRecurringSeries(ctx context.Context, id uuid.UUID) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, getRecurringSeries, id)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecurringSeries = `-- name: InsertRecurringSeries :one
INSERT INTO recurring_series (
    fingerprint,
    display_name,
    cadence,
    kind,
    status,
    amount_typical,
    amount_last,
    amount_changed,
    next_expected,
    uncertainty,
    member_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (fingerprint) DO NOTHING
RETURNING id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at
`

type InsertRecurringSeriesParams struct {
	Fingerprint   string          `json:"fingerprint"`
	DisplayName   string          `json:"display_name"`
	Cadence       string          `json:"cadence"`
	Kind          string          `json:"kind"`
	Status        string          `json:"status"`
	AmountTypical decimal.Decimal `json:"amount_typical"`
	AmountLast    decimal.Decimal `json:"amount_last"`
	AmountChanged bool            `json:"amount_changed"`
	NextExpected  pgtype.Date     `json:"next_expected"`
	Uncertainty   string          `json:"uncertainty"`
	MemberCount   int32           `json:"member_count"`
}

func (q *Queries) InsertRecurringSeries(ctx context.Context, arg InsertRecurringSeriesParams) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, insertRecurringSeries,
		arg.Fingerprint,
		arg.DisplayName,
		arg.Cadence,
		arg.Kind,
		arg.Status,
		arg.AmountTypical,
		arg.AmountLast,
		arg.AmountChanged,
		arg.NextExpected,
		arg.Uncertainty,
		arg.MemberCount,
	)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecurringSeriesMember = `-- name: InsertRecurringSeriesMember :exec
INSERT INTO recurring_series_members (
    series_id,
    transaction_id,
    booking_date,
    amount
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (transaction_id) DO NOTHING
`

type InsertRecurringSeriesMemberParams struct {
	SeriesID      uuid.UUID       `json:"series_id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	BookingDate   pgtype.Date     `json:"booking_date"`
	Amount        decimal.Decimal `json:"amount"`
}

func (q *Queries) InsertRecurringSeriesMember(ctx context.Context, arg InsertRecurringSeriesMemberParams) error {
	_, err := q.db.Exec(ctx, insertRecurringSeriesMember,
		arg.SeriesID,
		arg.TransactionID,
		arg.BookingDate,
		arg.Amount,
	)
	return err
}

const listRecurringMemberTransactionIDs = `-- name: ListRecurringMemberTransactionIDs :many
SELECT transaction_id
FROM recurring_series_members
`

func (q *Queries) ListRecurringMemberTransactionIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRecurringMemberTransactionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var transaction_id uuid.UUID
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringSeries = `-- name: ListRecurringSeries :many
SELECT id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at
FROM recurring_series
ORDER BY display_name ASC, created_at DESC
`

func (q *Queries) ListRecurringSeries(ctx context.Context) ([]RecurringSeries, error) {
	rows, err := q.db.Query(ctx, listRecurringSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringSeries{}
	for rows.Next() {
		var i RecurringSeries
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.DisplayName,
			&i.Cadence,
			&i.Kind,
			&i.Status,
			&i.AmountTypical,
			&i.AmountLast,
			&i.AmountChanged,
			&i.NextExpected,
			&i.Uncertainty,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForRecurringScan = `-- name: ListTransactionsForRecurringScan :many
SELECT
    id,
    account_id,
    booking_date,
    amount,
    purpose,
    booking_text,
    counterparty
FROM transactions
WHERE account_id IS NOT NULL
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForRecurringScanRow struct {
	ID           uuid.UUID       `json:"id"`
	AccountID    pgtype.UUID     `json:"account_id"`
	BookingDate  pgtype.Date     `json:"booking_date"`
	Amount       decimal.Decimal `json:"amount"`
	Purpose      string          `json:"purpose"`
	BookingText  string          `json:"booking_text"`
	Counterparty string          `json:"counterparty"`
}

func (q *Queries) ListTransactionsForRecurringScan(ctx context.Context) ([]ListTransactionsForRecurringScanRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForRecurringScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForRecurringScanRow{}
	for rows.Next() {
		var i ListTransactionsForRecurringScanRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BookingDate,
			&i.Amount,
			&i.Purpose,
			&i.BookingText,
			&i.Counterparty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUncertainRecurringSeries = `-- name: ListUncertainRecurringSeries :many
SELECT id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at
FROM recurring_series
WHERE status = 'uncertain'
ORDER BY amount_typical DESC, display_name ASC
`

func (q *Queries) ListUncertainRecurringSeries(ctx context.Context) ([]RecurringSeries, error) {
	rows, err := q.db.Query(ctx, listUncertainRecurringSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringSeries{}
	for rows.Next() {
		var i RecurringSeries
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.DisplayName,
			&i.Cadence,
			&i.Kind,
			&i.Status,
			&i.AmountTypical,
			&i.AmountLast,
			&i.AmountChanged,
			&i.NextExpected,
			&i.Uncertainty,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRecurringSeries = `-- name: RejectRecurringSeries :one
UPDATE recurring_series
SET
    status = 'ended',
    updated_at = now()
WHERE id = $1
  AND status = 'uncertain'
RETURNING id, fingerprint, display_name, cadence, kind, status, amount_typical, amount_last, amount_changed, next_expected, uncertainty, member_count, created_at, updated_at
`

func (q *Queries) RejectRecurringSeries(ctx context.Context, id uuid.UUID) (RecurringSeries, error) {
	row := q.db.QueryRow(ctx, rejectRecurringSeries, id)
	var i RecurringSeries
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.DisplayName,
		&i.Cadence,
		&i.Kind,
		&i.Status,
		&i.AmountTypical,
		&i.AmountLast,
		&i.AmountChanged,
		&i.NextExpected,
		&i.Uncertainty,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
