// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getCashflow = `-- name: GetCashflow :one
SELECT
  COALESCE(SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END), 0)::numeric AS income,
  COALESCE(SUM(CASE WHEN amount < 0 THEN -amount ELSE 0 END), 0)::numeric AS expenses,
  COALESCE(SUM(amount), 0)::numeric AS net
FROM transactions
WHERE booking_date >= $1::date
  AND booking_date <= $2::date
`

type GetCashflowParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetCashflowRow struct {
	Income   decimal.Decimal `json:"income"`
	Expenses decimal.Decimal `json:"expenses"`
	Net      decimal.Decimal `json:"net"`
}

func (q *Queries) GetCashflow(ctx context.Context, arg GetCashflowParams) (GetCashflowRow, error) {
	row := q.db.QueryRow(ctx, getCashflow, arg.FromDate, arg.ToDate)
	var i GetCashflowRow
	err := row.Scan(&i.Income, &i.Expenses, &i.Net)
	return i, err
}

const getCashflowV2 = `-- name: GetCashflowV2 :one
SELECT
  COALESCE(SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END), 0)::numeric AS income,
  COALESCE(SUM(CASE WHEN amount < 0 THEN -amount ELSE 0 END), 0)::numeric AS expenses,
  COALESCE(SUM(amount), 0)::numeric AS net
FROM transactions t
WHERE t.booking_date >= $1::date
  AND t.booking_date <= $2::date
  AND t.one_off = false
  AND NOT EXISTS (
    SELECT 1
    FROM transfer_pairs p
    WHERE p.status = 'confirmed'
      AND (p.tx_out_id = t.id OR p.tx_in_id = t.id)
  )
`

type GetCashflowV2Params struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetCashflowV2Row struct {
	Income   decimal.Decimal `json:"income"`
	Expenses decimal.Decimal `json:"expenses"`
	Net      decimal.Decimal `json:"net"`
}

func (q *Queries) GetCashflowV2(ctx context.Context, arg GetCashflowV2Params) (GetCashflowV2Row, error) {
	row := q.db.QueryRow(ctx, getCashflowV2, arg.FromDate, arg.ToDate)
	var i GetCashflowV2Row
	err := row.Scan(&i.Income, &i.Expenses, &i.Net)
	return i, err
}

const getLatestBookingDate = `-- name: GetLatestBookingDate :one
SELECT MAX(booking_date)::date AS latest_booking_date
FROM transactions
`

func (q *Queries) GetLatestBookingDate(ctx context.Context) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getLatestBookingDate)
	var latest_booking_date pgtype.Date
	err := row.Scan(&latest_booking_date)
	return latest_booking_date, err
}

const getOneOffExpenseImpact = `-- name: GetOneOffExpenseImpact :one
SELECT
  COUNT(*)::bigint AS one_off_count,
  COALESCE(SUM(-amount), 0)::numeric AS one_off_expense_total
FROM transactions
WHERE booking_date >= $1::date
  AND booking_date <= $2::date
  AND one_off = true
  AND amount < 0
`

type GetOneOffExpenseImpactParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetOneOffExpenseImpactRow struct {
	OneOffCount        int64           `json:"one_off_count"`
	OneOffExpenseTotal decimal.Decimal `json:"one_off_expense_total"`
}

func (q *Queries) GetOneOffExpenseImpact(ctx context.Context, arg GetOneOffExpenseImpactParams) (GetOneOffExpenseImpactRow, error) {
	row := q.db.QueryRow(ctx, getOneOffExpenseImpact, arg.FromDate, arg.ToDate)
	var i GetOneOffExpenseImpactRow
	err := row.Scan(&i.OneOffCount, &i.OneOffExpenseTotal)
	return i, err
}

const getTopCounterparties = `-- name: GetTopCounterparties :many
SELECT
  counterparty,
  SUM(-amount)::numeric AS total_spent,
  COUNT(*)::bigint AS transaction_count
FROM transactions
WHERE booking_date >= $1::date
  AND booking_date <= $2::date
  AND amount < 0
  AND counterparty <> ''
GROUP BY counterparty
ORDER BY total_spent DESC, counterparty ASC
LIMIT $3
`

type GetTopCounterpartiesParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	RowLimit int32       `json:"row_limit"`
}

type GetTopCounterpartiesRow struct {
	Counterparty     string          `json:"counterparty"`
	TotalSpent       decimal.Decimal `json:"total_spent"`
	TransactionCount int64           `json:"transaction_count"`
}

func (q *Queries) GetTopCounterparties(ctx context.Context, arg GetTopCounterpartiesParams) ([]GetTopCounterpartiesRow, error) {
	rows, err := q.db.Query(ctx, getTopCounterparties, arg.FromDate, arg.ToDate, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopCounterpartiesRow{}
	for rows.Next() {
		var i GetTopCounterpartiesRow
		if err := rows.Scan(&i.Counterparty, &i.TotalSpent, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsInPeriod = `-- name: ListAccountsInPeriod :many
SELECT DISTINCT COALESCE(a.display_name, t.order_account, 'unknown')::text AS account_name
FROM transactions t
LEFT JOIN accounts a ON a.id = t.account_id
WHERE t.booking_date >= $1::date
  AND t.booking_date <= $2::date
ORDER BY account_name ASC
`

type ListAccountsInPeriodParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListAccountsInPeriod(ctx context.Context, arg ListAccountsInPeriodParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountsInPeriod, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var account_name string
		if err := rows.Scan(&account_name); err != nil {
			return nil, err
		}
		items = append(items, account_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashflowV2TransactionIDs = `-- name: ListCashflowV2TransactionIDs :many
SELECT t.id
FROM transactions t
WHERE t.booking_date >= $1::date
  AND t.booking_date <= $2::date
  AND t.one_off = false
  AND NOT EXISTS (
    SELECT 1
    FROM transfer_pairs p
    WHERE p.status = 'confirmed'
      AND (p.tx_out_id = t.id OR p.tx_in_id = t.id)
  )
ORDER BY t.booking_date ASC, t.id ASC
LIMIT $3
`

type ListCashflowV2TransactionIDsParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListCashflowV2TransactionIDs(ctx context.Context, arg ListCashflowV2TransactionIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCashflowV2TransactionIDs, arg.FromDate, arg.ToDate, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategorySpendInPeriod = `-- name: ListCategorySpendInPeriod :many
SELECT
  c.slug AS category_slug,
  c.display_name AS category_name,
  COALESCE(SUM(-t.amount), 0)::numeric AS total,
  COUNT(*)::bigint AS transaction_count
FROM transactions t
JOIN transaction_classifications tc ON tc.transaction_id = t.id
JOIN categories c ON c.id = tc.category_id
WHERE t.booking_date >= $1::date
  AND t.booking_date <= $2::date
  AND t.amount < 0
  AND t.one_off = false
  AND NOT EXISTS (
    SELECT 1
    FROM transfer_pairs p
    WHERE p.status = 'confirmed'
      AND (p.tx_out_id = t.id OR p.tx_in_id = t.id)
  )
GROUP BY c.slug, c.display_name
ORDER BY total DESC, c.display_name ASC
LIMIT $3
`

type ListCategorySpendInPeriodParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	RowLimit int32       `json:"row_limit"`
}

type ListCategorySpendInPeriodRow struct {
	CategorySlug     string          `json:"category_slug"`
	CategoryName     string          `json:"category_name"`
	Total            decimal.Decimal `json:"total"`
	TransactionCount int64           `json:"transaction_count"`
}

func (q *Queries) ListCategorySpendInPeriod(ctx context.Context, arg ListCategorySpendInPeriodParams) ([]ListCategorySpendInPeriodRow, error) {
	rows, err := q.db.Query(ctx, listCategorySpendInPeriod, arg.FromDate, arg.ToDate, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategorySpendInPeriodRow{}
	for rows.Next() {
		var i ListCategorySpendInPeriodRow
		if err := rows.Scan(
			&i.CategorySlug,
			&i.CategoryName,
			&i.Total,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedTransferIDsInPeriod = `-- name: ListConfirmedTransferIDsInPeriod :many
SELECT p.id
FROM transfer_pairs p
JOIN transactions out_tx ON out_tx.id = p.tx_out_id
JOIN transactions in_tx ON in_tx.id = p.tx_in_id
WHERE p.status = 'confirmed'
  AND (
    (out_tx.booking_date >= $1::date AND out_tx.booking_date <= $2::date)
    OR (in_tx.booking_date >= $1::date AND in_tx.booking_date <= $2::date)
  )
ORDER BY p.created_at ASC
`

type ListConfirmedTransferIDsInPeriodParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListConfirmedTransferIDsInPeriod(ctx context.Context, arg ListConfirmedTransferIDsInPeriodParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listConfirmedTransferIDsInPeriod, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyCashflowV2 = `-- name: ListMonthlyCashflowV2 :many
SELECT
  date_trunc('month', t.booking_date)::date AS month_start,
  COALESCE(SUM(CASE WHEN t.amount > 0 THEN t.amount ELSE 0 END), 0)::numeric AS income,
  COALESCE(SUM(CASE WHEN t.amount < 0 THEN -t.amount ELSE 0 END), 0)::numeric AS expenses,
  COALESCE(SUM(t.amount), 0)::numeric AS net
FROM transactions t
WHERE t.booking_date >= $1::date
  AND t.booking_date <= $2::date
  AND t.one_off = false
  AND NOT EXISTS (
    SELECT 1
    FROM transfer_pairs p
    WHERE p.status = 'confirmed'
      AND (p.tx_out_id = t.id OR p.tx_in_id = t.id)
  )
GROUP BY 1
ORDER BY 1 ASC
`

type ListMonthlyCashflowV2Params struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ListMonthlyCashflowV2Row struct {
	MonthStart pgtype.Date     `json:"month_start"`
	Income     decimal.Decimal `json:"income"`
	Expenses   decimal.Decimal `json:"expenses"`
	Net        decimal.Decimal `json:"net"`
}

func (q *Queries) ListMonthlyCashflowV2(ctx context.Context, arg ListMonthlyCashflowV2Params) ([]ListMonthlyCashflowV2Row, error) {
	rows, err := q.db.Query(ctx, listMonthlyCashflowV2, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlyCashflowV2Row{}
	for rows.Next() {
		var i ListMonthlyCashflowV2Row
		if err := rows.Scan(
			&i.MonthStart,
			&i.Income,
			&i.Expenses,
			&i.Net,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
