// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getCashflow = `-- name: GetCashflow :one
SELECT
  COALESCE(SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END), 0)::numeric AS income,
  COALESCE(SUM(CASE WHEN amount < 0 THEN -amount ELSE 0 END), 0)::numeric AS expenses,
  COALESCE(SUM(amount), 0)::numeric AS net
FROM transactions
WHERE booking_date >= $1::date
  AND booking_date <= $2::date
`

type GetCashflowParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetCashflowRow struct {
	Income   decimal.Decimal `json:"income"`
	Expenses decimal.Decimal `json:"expenses"`
	Net      decimal.Decimal `json:"net"`
}

func (q *Queries) GetCashflow(ctx context.Context, arg GetCashflowParams) (GetCashflowRow, error) {
	row := q.db.QueryRow(ctx, getCashflow, arg.FromDate, arg.ToDate)
	var i GetCashflowRow
	err := row.Scan(&i.Income, &i.Expenses, &i.Net)
	return i, err
}

const getCashflowV2 = `-- name: GetCashflowV2 :one
SELECT
  COALESCE(SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END), 0)::numeric AS income,
  COALESCE(SUM(CASE WHEN amount < 0 THEN -amount ELSE 0 END), 0)::numeric AS expenses,
  COALESCE(SUM(amount), 0)::numeric AS net
FROM transactions t
WHERE t.booking_date >= $1::date
  AND t.booking_date <= $2::date
  AND NOT EXISTS (
    SELECT 1
    FROM transfer_pairs p
    WHERE p.status = 'confirmed'
      AND (p.tx_out_id = t.id OR p.tx_in_id = t.id)
  )
`

type GetCashflowV2Params struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetCashflowV2Row struct {
	Income   decimal.Decimal `json:"income"`
	Expenses decimal.Decimal `json:"expenses"`
	Net      decimal.Decimal `json:"net"`
}

func (q *Queries) GetCashflowV2(ctx context.Context, arg GetCashflowV2Params) (GetCashflowV2Row, error) {
	row := q.db.QueryRow(ctx, getCashflowV2, arg.FromDate, arg.ToDate)
	var i GetCashflowV2Row
	err := row.Scan(&i.Income, &i.Expenses, &i.Net)
	return i, err
}

const getTopCounterparties = `-- name: GetTopCounterparties :many
SELECT
  counterparty,
  SUM(-amount)::numeric AS total_spent,
  COUNT(*)::bigint AS transaction_count
FROM transactions
WHERE booking_date >= $1::date
  AND booking_date <= $2::date
  AND amount < 0
  AND counterparty <> ''
GROUP BY counterparty
ORDER BY total_spent DESC, counterparty ASC
LIMIT $3
`

type GetTopCounterpartiesParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	RowLimit int32       `json:"row_limit"`
}

type GetTopCounterpartiesRow struct {
	Counterparty     string          `json:"counterparty"`
	TotalSpent       decimal.Decimal `json:"total_spent"`
	TransactionCount int64           `json:"transaction_count"`
}

func (q *Queries) GetTopCounterparties(ctx context.Context, arg GetTopCounterpartiesParams) ([]GetTopCounterpartiesRow, error) {
	rows, err := q.db.Query(ctx, getTopCounterparties, arg.FromDate, arg.ToDate, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopCounterpartiesRow{}
	for rows.Next() {
		var i GetTopCounterpartiesRow
		if err := rows.Scan(&i.Counterparty, &i.TotalSpent, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
