// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmMoneyReview = `-- name: ConfirmMoneyReview :one
UPDATE money_reviews
SET
    status = 'confirmed',
    confirmed_at = now(),
    updated_at = now()
WHERE id = $1
  AND status IN ('draft', 'needs_confirmation')
RETURNING id, baseline_id, period_from, period_to, status, summary, findings, data_freshness, confirmed_at, created_at, updated_at
`

func (q *Queries) ConfirmMoneyReview(ctx context.Context, id uuid.UUID) (MoneyReview, error) {
	row := q.db.QueryRow(ctx, confirmMoneyReview, id)
	var i MoneyReview
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.Summary,
		&i.Findings,
		&i.DataFreshness,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMoneyReview = `-- name: GetMoneyReview :one
SELECT id, baseline_id, period_from, period_to, status, summary, findings, data_freshness, confirmed_at, created_at, updated_at
FROM money_reviews
WHERE id = $1
`

func (q *Queries) GetMoneyReview(ctx context.Context, id uuid.UUID) (MoneyReview, error) {
	row := q.db.QueryRow(ctx, getMoneyReview, id)
	var i MoneyReview
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.Summary,
		&i.Findings,
		&i.DataFreshness,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMoneyReview = `-- name: InsertMoneyReview :one
INSERT INTO money_reviews (
    baseline_id,
    period_from,
    period_to,
    status,
    summary,
    findings,
    data_freshness
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, baseline_id, period_from, period_to, status, summary, findings, data_freshness, confirmed_at, created_at, updated_at
`

type InsertMoneyReviewParams struct {
	BaselineID    uuid.UUID   `json:"baseline_id"`
	PeriodFrom    pgtype.Date `json:"period_from"`
	PeriodTo      pgtype.Date `json:"period_to"`
	Status        string      `json:"status"`
	Summary       string      `json:"summary"`
	Findings      []byte      `json:"findings"`
	DataFreshness string      `json:"data_freshness"`
}

func (q *Queries) InsertMoneyReview(ctx context.Context, arg InsertMoneyReviewParams) (MoneyReview, error) {
	row := q.db.QueryRow(ctx, insertMoneyReview,
		arg.BaselineID,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.Status,
		arg.Summary,
		arg.Findings,
		arg.DataFreshness,
	)
	var i MoneyReview
	err := row.Scan(
		&i.ID,
		&i.BaselineID,
		&i.PeriodFrom,
		&i.PeriodTo,
		&i.Status,
		&i.Summary,
		&i.Findings,
		&i.DataFreshness,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMoneyReviews = `-- name: ListMoneyReviews :many
SELECT id, baseline_id, period_from, period_to, status, summary, findings, data_freshness, confirmed_at, created_at, updated_at
FROM money_reviews
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListMoneyReviews(ctx context.Context, rowLimit int32) ([]MoneyReview, error) {
	rows, err := q.db.Query(ctx, listMoneyReviews, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MoneyReview{}
	for rows.Next() {
		var i MoneyReview
		if err := rows.Scan(
			&i.ID,
			&i.BaselineID,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Status,
			&i.Summary,
			&i.Findings,
			&i.DataFreshness,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeOpenMoneyReviews = `-- name: SupersedeOpenMoneyReviews :exec
UPDATE money_reviews
SET
    status = 'superseded',
    updated_at = now()
WHERE status IN ('draft', 'needs_confirmation', 'confirmed')
`

func (q *Queries) SupersedeOpenMoneyReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, supersedeOpenMoneyReviews)
	return err
}
