// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*)::bigint AS count FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsFiltered = `-- name: CountTransactionsFiltered :one
SELECT COUNT(*)::bigint AS count
FROM transactions
WHERE ($1::date IS NULL OR booking_date >= $1::date)
  AND ($2::date IS NULL OR booking_date <= $2::date)
`

type CountTransactionsFilteredParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) CountTransactionsFiltered(ctx context.Context, arg CountTransactionsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsFiltered, arg.FromDate, arg.ToDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    order_account,
    booking_date,
    value_date,
    booking_text,
    purpose,
    creditor_id,
    mandate_reference,
    end_to_end_reference,
    collection_reference,
    direct_debit_original_amount,
    chargeback_expense_reimbursement,
    counterparty,
    counterparty_iban,
    counterparty_bic,
    amount,
    currency,
    info,
    fingerprint
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id
`

type InsertTransactionParams struct {
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.OrderAccount,
		arg.BookingDate,
		arg.ValueDate,
		arg.BookingText,
		arg.Purpose,
		arg.CreditorID,
		arg.MandateReference,
		arg.EndToEndReference,
		arg.CollectionReference,
		arg.DirectDebitOriginalAmount,
		arg.ChargebackExpenseReimbursement,
		arg.Counterparty,
		arg.CounterpartyIban,
		arg.CounterpartyBic,
		arg.Amount,
		arg.Currency,
		arg.Info,
		arg.Fingerprint,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTransactionIfNew = `-- name: InsertTransactionIfNew :one
INSERT INTO transactions (
    order_account,
    booking_date,
    value_date,
    booking_text,
    purpose,
    creditor_id,
    mandate_reference,
    end_to_end_reference,
    collection_reference,
    direct_debit_original_amount,
    chargeback_expense_reimbursement,
    counterparty,
    counterparty_iban,
    counterparty_bic,
    amount,
    currency,
    info,
    fingerprint
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (fingerprint) DO NOTHING
RETURNING id
`

type InsertTransactionIfNewParams struct {
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
}

func (q *Queries) InsertTransactionIfNew(ctx context.Context, arg InsertTransactionIfNewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTransactionIfNew,
		arg.OrderAccount,
		arg.BookingDate,
		arg.ValueDate,
		arg.BookingText,
		arg.Purpose,
		arg.CreditorID,
		arg.MandateReference,
		arg.EndToEndReference,
		arg.CollectionReference,
		arg.DirectDebitOriginalAmount,
		arg.ChargebackExpenseReimbursement,
		arg.Counterparty,
		arg.CounterpartyIban,
		arg.CounterpartyBic,
		arg.Amount,
		arg.Currency,
		arg.Info,
		arg.Fingerprint,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    id,
    order_account,
    booking_date,
    value_date,
    booking_text,
    purpose,
    creditor_id,
    mandate_reference,
    end_to_end_reference,
    collection_reference,
    direct_debit_original_amount,
    chargeback_expense_reimbursement,
    counterparty,
    counterparty_iban,
    counterparty_bic,
    amount,
    currency,
    info,
    fingerprint
FROM transactions
WHERE ($1::date IS NULL OR booking_date >= $1::date)
  AND ($2::date IS NULL OR booking_date <= $2::date)
ORDER BY booking_date DESC
LIMIT $4 OFFSET $3
`

type ListTransactionsParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.FromDate,
		arg.ToDate,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.OrderAccount,
			&i.BookingDate,
			&i.ValueDate,
			&i.BookingText,
			&i.Purpose,
			&i.CreditorID,
			&i.MandateReference,
			&i.EndToEndReference,
			&i.CollectionReference,
			&i.DirectDebitOriginalAmount,
			&i.ChargebackExpenseReimbursement,
			&i.Counterparty,
			&i.CounterpartyIban,
			&i.CounterpartyBic,
			&i.Amount,
			&i.Currency,
			&i.Info,
			&i.Fingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
