// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getTransferPair = `-- name: GetTransferPair :one
SELECT id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at
FROM transfer_pairs
WHERE id = $1
`

func (q *Queries) GetTransferPair(ctx context.Context, id uuid.UUID) (TransferPair, error) {
	row := q.db.QueryRow(ctx, getTransferPair, id)
	var i TransferPair
	err := row.Scan(
		&i.ID,
		&i.TxOutID,
		&i.TxInID,
		&i.Status,
		&i.Confidence,
		&i.Rationale,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransferPair = `-- name: InsertTransferPair :one
INSERT INTO transfer_pairs (
    tx_out_id,
    tx_in_id,
    status,
    confidence,
    rationale
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (tx_out_id, tx_in_id) DO NOTHING
RETURNING id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at
`

type InsertTransferPairParams struct {
	TxOutID    uuid.UUID `json:"tx_out_id"`
	TxInID     uuid.UUID `json:"tx_in_id"`
	Status     string    `json:"status"`
	Confidence string    `json:"confidence"`
	Rationale  []byte    `json:"rationale"`
}

func (q *Queries) InsertTransferPair(ctx context.Context, arg InsertTransferPairParams) (TransferPair, error) {
	row := q.db.QueryRow(ctx, insertTransferPair,
		arg.TxOutID,
		arg.TxInID,
		arg.Status,
		arg.Confidence,
		arg.Rationale,
	)
	var i TransferPair
	err := row.Scan(
		&i.ID,
		&i.TxOutID,
		&i.TxInID,
		&i.Status,
		&i.Confidence,
		&i.Rationale,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsForTransferScan = `-- name: ListTransactionsForTransferScan :many
SELECT
    id,
    account_id,
    booking_date,
    amount,
    purpose,
    booking_text,
    counterparty,
    counterparty_iban
FROM transactions
WHERE account_id IS NOT NULL
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForTransferScanRow struct {
	ID               uuid.UUID       `json:"id"`
	AccountID        pgtype.UUID     `json:"account_id"`
	BookingDate      pgtype.Date     `json:"booking_date"`
	Amount           decimal.Decimal `json:"amount"`
	Purpose          string          `json:"purpose"`
	BookingText      string          `json:"booking_text"`
	Counterparty     string          `json:"counterparty"`
	CounterpartyIban pgtype.Text     `json:"counterparty_iban"`
}

func (q *Queries) ListTransactionsForTransferScan(ctx context.Context) ([]ListTransactionsForTransferScanRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForTransferScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForTransferScanRow{}
	for rows.Next() {
		var i ListTransactionsForTransferScanRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BookingDate,
			&i.Amount,
			&i.Purpose,
			&i.BookingText,
			&i.Counterparty,
			&i.CounterpartyIban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferPairLegs = `-- name: ListTransferPairLegs :many
SELECT tx_out_id, tx_in_id
FROM transfer_pairs
`

type ListTransferPairLegsRow struct {
	TxOutID uuid.UUID `json:"tx_out_id"`
	TxInID  uuid.UUID `json:"tx_in_id"`
}

func (q *Queries) ListTransferPairLegs(ctx context.Context) ([]ListTransferPairLegsRow, error) {
	rows, err := q.db.Query(ctx, listTransferPairLegs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferPairLegsRow{}
	for rows.Next() {
		var i ListTransferPairLegsRow
		if err := rows.Scan(&i.TxOutID, &i.TxInID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferPairs = `-- name: ListTransferPairs :many
SELECT id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at
FROM transfer_pairs
ORDER BY created_at DESC
`

func (q *Queries) ListTransferPairs(ctx context.Context) ([]TransferPair, error) {
	rows, err := q.db.Query(ctx, listTransferPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferPair{}
	for rows.Next() {
		var i TransferPair
		if err := rows.Scan(
			&i.ID,
			&i.TxOutID,
			&i.TxInID,
			&i.Status,
			&i.Confidence,
			&i.Rationale,
			&i.ConfirmedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
