// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*)::bigint AS count FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsFiltered = `-- name: CountTransactionsFiltered :one
SELECT COUNT(*)::bigint AS count
FROM transactions
WHERE ($1::date IS NULL OR booking_date >= $1::date)
  AND ($2::date IS NULL OR booking_date <= $2::date)
  AND ($3::text IS NULL OR order_account = $3)
  AND ($4::text IS NULL OR counterparty ILIKE $4 || '%')
  AND ($5::numeric IS NULL OR amount >= $5::numeric)
  AND ($6::numeric IS NULL OR amount <= $6::numeric)
  AND (
    $7::text IS NULL
    OR purpose ILIKE '%' || $7 || '%'
    OR counterparty ILIKE '%' || $7 || '%'
    OR booking_text ILIKE '%' || $7 || '%'
  )
`

type CountTransactionsFilteredParams struct {
	FromDate     pgtype.Date    `json:"from_date"`
	ToDate       pgtype.Date    `json:"to_date"`
	Account      pgtype.Text    `json:"account"`
	Counterparty pgtype.Text    `json:"counterparty"`
	MinAmount    pgtype.Numeric `json:"min_amount"`
	MaxAmount    pgtype.Numeric `json:"max_amount"`
	Search       pgtype.Text    `json:"search"`
}

func (q *Queries) CountTransactionsFiltered(ctx context.Context, arg CountTransactionsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsFiltered,
		arg.FromDate,
		arg.ToDate,
		arg.Account,
		arg.Counterparty,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    order_account,
    booking_date,
    value_date,
    booking_text,
    purpose,
    creditor_id,
    mandate_reference,
    end_to_end_reference,
    collection_reference,
    direct_debit_original_amount,
    chargeback_expense_reimbursement,
    counterparty,
    counterparty_iban,
    counterparty_bic,
    amount,
    currency,
    info,
    fingerprint,
    account_id,
    import_run_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id
`

type InsertTransactionParams struct {
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
	AccountID                      pgtype.UUID     `json:"account_id"`
	ImportRunID                    pgtype.UUID     `json:"import_run_id"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.OrderAccount,
		arg.BookingDate,
		arg.ValueDate,
		arg.BookingText,
		arg.Purpose,
		arg.CreditorID,
		arg.MandateReference,
		arg.EndToEndReference,
		arg.CollectionReference,
		arg.DirectDebitOriginalAmount,
		arg.ChargebackExpenseReimbursement,
		arg.Counterparty,
		arg.CounterpartyIban,
		arg.CounterpartyBic,
		arg.Amount,
		arg.Currency,
		arg.Info,
		arg.Fingerprint,
		arg.AccountID,
		arg.ImportRunID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTransactionIfNew = `-- name: InsertTransactionIfNew :one
INSERT INTO transactions (
    order_account,
    booking_date,
    value_date,
    booking_text,
    purpose,
    creditor_id,
    mandate_reference,
    end_to_end_reference,
    collection_reference,
    direct_debit_original_amount,
    chargeback_expense_reimbursement,
    counterparty,
    counterparty_iban,
    counterparty_bic,
    amount,
    currency,
    info,
    fingerprint,
    account_id,
    import_run_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
ON CONFLICT (fingerprint) DO NOTHING
RETURNING id
`

type InsertTransactionIfNewParams struct {
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
	AccountID                      pgtype.UUID     `json:"account_id"`
	ImportRunID                    pgtype.UUID     `json:"import_run_id"`
}

func (q *Queries) InsertTransactionIfNew(ctx context.Context, arg InsertTransactionIfNewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTransactionIfNew,
		arg.OrderAccount,
		arg.BookingDate,
		arg.ValueDate,
		arg.BookingText,
		arg.Purpose,
		arg.CreditorID,
		arg.MandateReference,
		arg.EndToEndReference,
		arg.CollectionReference,
		arg.DirectDebitOriginalAmount,
		arg.ChargebackExpenseReimbursement,
		arg.Counterparty,
		arg.CounterpartyIban,
		arg.CounterpartyBic,
		arg.Amount,
		arg.Currency,
		arg.Info,
		arg.Fingerprint,
		arg.AccountID,
		arg.ImportRunID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id,
    t.order_account,
    t.booking_date,
    t.value_date,
    t.booking_text,
    t.purpose,
    t.creditor_id,
    t.mandate_reference,
    t.end_to_end_reference,
    t.collection_reference,
    t.direct_debit_original_amount,
    t.chargeback_expense_reimbursement,
    t.counterparty,
    t.counterparty_iban,
    t.counterparty_bic,
    t.amount,
    t.currency,
    t.info,
    t.fingerprint,
    t.account_id,
    t.import_run_id,
    t.one_off,
    EXISTS (
        SELECT 1
        FROM recurring_series_members m
        WHERE m.transaction_id = t.id
    ) AS recurring
FROM transactions t
WHERE ($1::date IS NULL OR t.booking_date >= $1::date)
  AND ($2::date IS NULL OR t.booking_date <= $2::date)
  AND ($3::text IS NULL OR t.order_account = $3)
  AND ($4::text IS NULL OR t.counterparty ILIKE $4 || '%')
  AND ($5::numeric IS NULL OR t.amount >= $5::numeric)
  AND ($6::numeric IS NULL OR t.amount <= $6::numeric)
  AND (
    $7::text IS NULL
    OR t.purpose ILIKE '%' || $7 || '%'
    OR t.counterparty ILIKE '%' || $7 || '%'
    OR t.booking_text ILIKE '%' || $7 || '%'
  )
ORDER BY
  CASE WHEN $8 = 'amount' AND COALESCE($9, false) THEN t.amount END ASC NULLS LAST,
  CASE WHEN $8 = 'amount' AND NOT COALESCE($9, false) THEN t.amount END DESC NULLS LAST,
  CASE WHEN $8 = 'counterparty' AND COALESCE($9, false) THEN t.counterparty END ASC NULLS LAST,
  CASE WHEN $8 = 'counterparty' AND NOT COALESCE($9, false) THEN t.counterparty END DESC NULLS LAST,
  CASE WHEN ($8 IS NULL OR $8 = 'booking_date') AND COALESCE($9, false) THEN t.booking_date END ASC NULLS LAST,
  CASE WHEN ($8 IS NULL OR $8 = 'booking_date') AND NOT COALESCE($9, false) THEN t.booking_date END DESC NULLS LAST
LIMIT $11 OFFSET $10
`

type ListTransactionsParams struct {
	FromDate     pgtype.Date    `json:"from_date"`
	ToDate       pgtype.Date    `json:"to_date"`
	Account      pgtype.Text    `json:"account"`
	Counterparty pgtype.Text    `json:"counterparty"`
	MinAmount    pgtype.Numeric `json:"min_amount"`
	MaxAmount    pgtype.Numeric `json:"max_amount"`
	Search       pgtype.Text    `json:"search"`
	SortField    interface{}    `json:"sort_field"`
	SortAsc      interface{}    `json:"sort_asc"`
	Offset       int32          `json:"offset"`
	Limit        int32          `json:"limit"`
}

type ListTransactionsRow struct {
	ID                             uuid.UUID       `json:"id"`
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
	AccountID                      pgtype.UUID     `json:"account_id"`
	ImportRunID                    pgtype.UUID     `json:"import_run_id"`
	OneOff                         bool            `json:"one_off"`
	Recurring                      bool            `json:"recurring"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.FromDate,
		arg.ToDate,
		arg.Account,
		arg.Counterparty,
		arg.MinAmount,
		arg.MaxAmount,
		arg.Search,
		arg.SortField,
		arg.SortAsc,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderAccount,
			&i.BookingDate,
			&i.ValueDate,
			&i.BookingText,
			&i.Purpose,
			&i.CreditorID,
			&i.MandateReference,
			&i.EndToEndReference,
			&i.CollectionReference,
			&i.DirectDebitOriginalAmount,
			&i.ChargebackExpenseReimbursement,
			&i.Counterparty,
			&i.CounterpartyIban,
			&i.CounterpartyBic,
			&i.Amount,
			&i.Currency,
			&i.Info,
			&i.Fingerprint,
			&i.AccountID,
			&i.ImportRunID,
			&i.OneOff,
			&i.Recurring,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionOneOff = `-- name: SetTransactionOneOff :one
WITH updated AS (
    UPDATE transactions
    SET one_off = $2
    WHERE id = $1
    RETURNING
        id,
        order_account,
        booking_date,
        value_date,
        booking_text,
        purpose,
        creditor_id,
        mandate_reference,
        end_to_end_reference,
        collection_reference,
        direct_debit_original_amount,
        chargeback_expense_reimbursement,
        counterparty,
        counterparty_iban,
        counterparty_bic,
        amount,
        currency,
        info,
        fingerprint,
        account_id,
        import_run_id,
        one_off
)
SELECT
    updated.id,
    updated.order_account,
    updated.booking_date,
    updated.value_date,
    updated.booking_text,
    updated.purpose,
    updated.creditor_id,
    updated.mandate_reference,
    updated.end_to_end_reference,
    updated.collection_reference,
    updated.direct_debit_original_amount,
    updated.chargeback_expense_reimbursement,
    updated.counterparty,
    updated.counterparty_iban,
    updated.counterparty_bic,
    updated.amount,
    updated.currency,
    updated.info,
    updated.fingerprint,
    updated.account_id,
    updated.import_run_id,
    updated.one_off,
    EXISTS (
        SELECT 1
        FROM recurring_series_members m
        WHERE m.transaction_id = updated.id
    ) AS recurring
FROM updated
`

type SetTransactionOneOffParams struct {
	ID     uuid.UUID `json:"id"`
	OneOff bool      `json:"one_off"`
}

type SetTransactionOneOffRow struct {
	ID                             uuid.UUID       `json:"id"`
	OrderAccount                   string          `json:"order_account"`
	BookingDate                    pgtype.Date     `json:"booking_date"`
	ValueDate                      pgtype.Date     `json:"value_date"`
	BookingText                    string          `json:"booking_text"`
	Purpose                        string          `json:"purpose"`
	CreditorID                     string          `json:"creditor_id"`
	MandateReference               string          `json:"mandate_reference"`
	EndToEndReference              string          `json:"end_to_end_reference"`
	CollectionReference            string          `json:"collection_reference"`
	DirectDebitOriginalAmount      string          `json:"direct_debit_original_amount"`
	ChargebackExpenseReimbursement string          `json:"chargeback_expense_reimbursement"`
	Counterparty                   string          `json:"counterparty"`
	CounterpartyIban               pgtype.Text     `json:"counterparty_iban"`
	CounterpartyBic                pgtype.Text     `json:"counterparty_bic"`
	Amount                         decimal.Decimal `json:"amount"`
	Currency                       string          `json:"currency"`
	Info                           string          `json:"info"`
	Fingerprint                    string          `json:"fingerprint"`
	AccountID                      pgtype.UUID     `json:"account_id"`
	ImportRunID                    pgtype.UUID     `json:"import_run_id"`
	OneOff                         bool            `json:"one_off"`
	Recurring                      bool            `json:"recurring"`
}

func (q *Queries) SetTransactionOneOff(ctx context.Context, arg SetTransactionOneOffParams) (SetTransactionOneOffRow, error) {
	row := q.db.QueryRow(ctx, setTransactionOneOff, arg.ID, arg.OneOff)
	var i SetTransactionOneOffRow
	err := row.Scan(
		&i.ID,
		&i.OrderAccount,
		&i.BookingDate,
		&i.ValueDate,
		&i.BookingText,
		&i.Purpose,
		&i.CreditorID,
		&i.MandateReference,
		&i.EndToEndReference,
		&i.CollectionReference,
		&i.DirectDebitOriginalAmount,
		&i.ChargebackExpenseReimbursement,
		&i.Counterparty,
		&i.CounterpartyIban,
		&i.CounterpartyBic,
		&i.Amount,
		&i.Currency,
		&i.Info,
		&i.Fingerprint,
		&i.AccountID,
		&i.ImportRunID,
		&i.OneOff,
		&i.Recurring,
	)
	return i, err
}
