// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const confirmTransferPair = `-- name: ConfirmTransferPair :one
UPDATE transfer_pairs
SET
    status = 'confirmed',
    confirmed_at = now()
WHERE id = $1
  AND household_id = $2
  AND status = 'suggested'
RETURNING id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at, household_id
`

type ConfirmTransferPairParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) ConfirmTransferPair(ctx context.Context, arg ConfirmTransferPairParams) (TransferPair, error) {
	row := q.db.QueryRow(ctx, confirmTransferPair, arg.ID, arg.HouseholdID)
	var i TransferPair
	err := row.Scan(
		&i.ID,
		&i.TxOutID,
		&i.TxInID,
		&i.Status,
		&i.Confidence,
		&i.Rationale,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const getTransferPair = `-- name: GetTransferPair :one
SELECT id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at, household_id
FROM transfer_pairs
WHERE id = $1 AND household_id = $2
`

type GetTransferPairParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetTransferPair(ctx context.Context, arg GetTransferPairParams) (TransferPair, error) {
	row := q.db.QueryRow(ctx, getTransferPair, arg.ID, arg.HouseholdID)
	var i TransferPair
	err := row.Scan(
		&i.ID,
		&i.TxOutID,
		&i.TxInID,
		&i.Status,
		&i.Confidence,
		&i.Rationale,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const insertTransferPair = `-- name: InsertTransferPair :one
INSERT INTO transfer_pairs (
    household_id,
    tx_out_id,
    tx_in_id,
    status,
    confidence,
    rationale
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (tx_out_id, tx_in_id) DO NOTHING
RETURNING id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at, household_id
`

type InsertTransferPairParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	TxOutID     uuid.UUID `json:"tx_out_id"`
	TxInID      uuid.UUID `json:"tx_in_id"`
	Status      string    `json:"status"`
	Confidence  string    `json:"confidence"`
	Rationale   []byte    `json:"rationale"`
}

func (q *Queries) InsertTransferPair(ctx context.Context, arg InsertTransferPairParams) (TransferPair, error) {
	row := q.db.QueryRow(ctx, insertTransferPair,
		arg.HouseholdID,
		arg.TxOutID,
		arg.TxInID,
		arg.Status,
		arg.Confidence,
		arg.Rationale,
	)
	var i TransferPair
	err := row.Scan(
		&i.ID,
		&i.TxOutID,
		&i.TxInID,
		&i.Status,
		&i.Confidence,
		&i.Rationale,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}

const listSuggestedTransferCandidates = `-- name: ListSuggestedTransferCandidates :many
SELECT
    p.id,
    p.status,
    p.confidence,
    p.created_at,
    out_tx.id AS tx_out_id,
    out_tx.amount AS out_amount,
    out_tx.booking_date AS out_booking_date,
    out_tx.booking_text AS out_booking_text,
    out_tx.purpose AS out_purpose,
    out_tx.counterparty AS out_counterparty,
    COALESCE(out_acc.display_name, '') AS out_account_name,
    in_tx.id AS tx_in_id,
    in_tx.amount AS in_amount,
    in_tx.booking_date AS in_booking_date,
    in_tx.booking_text AS in_booking_text,
    in_tx.purpose AS in_purpose,
    in_tx.counterparty AS in_counterparty,
    COALESCE(in_acc.display_name, '') AS in_account_name
FROM transfer_pairs p
JOIN transactions out_tx ON out_tx.id = p.tx_out_id
JOIN transactions in_tx ON in_tx.id = p.tx_in_id
LEFT JOIN accounts out_acc ON out_acc.id = out_tx.account_id
LEFT JOIN accounts in_acc ON in_acc.id = in_tx.account_id
WHERE p.household_id = $1
  AND p.status = 'suggested'
ORDER BY p.created_at DESC
`

type ListSuggestedTransferCandidatesRow struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	Confidence      string             `json:"confidence"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TxOutID         uuid.UUID          `json:"tx_out_id"`
	OutAmount       decimal.Decimal    `json:"out_amount"`
	OutBookingDate  pgtype.Date        `json:"out_booking_date"`
	OutBookingText  string             `json:"out_booking_text"`
	OutPurpose      string             `json:"out_purpose"`
	OutCounterparty string             `json:"out_counterparty"`
	OutAccountName  string             `json:"out_account_name"`
	TxInID          uuid.UUID          `json:"tx_in_id"`
	InAmount        decimal.Decimal    `json:"in_amount"`
	InBookingDate   pgtype.Date        `json:"in_booking_date"`
	InBookingText   string             `json:"in_booking_text"`
	InPurpose       string             `json:"in_purpose"`
	InCounterparty  string             `json:"in_counterparty"`
	InAccountName   string             `json:"in_account_name"`
}

func (q *Queries) ListSuggestedTransferCandidates(ctx context.Context, householdID uuid.UUID) ([]ListSuggestedTransferCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSuggestedTransferCandidates, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuggestedTransferCandidatesRow{}
	for rows.Next() {
		var i ListSuggestedTransferCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Confidence,
			&i.CreatedAt,
			&i.TxOutID,
			&i.OutAmount,
			&i.OutBookingDate,
			&i.OutBookingText,
			&i.OutPurpose,
			&i.OutCounterparty,
			&i.OutAccountName,
			&i.TxInID,
			&i.InAmount,
			&i.InBookingDate,
			&i.InBookingText,
			&i.InPurpose,
			&i.InCounterparty,
			&i.InAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForTransferScan = `-- name: ListTransactionsForTransferScan :many
SELECT
    id,
    account_id,
    booking_date,
    amount,
    purpose,
    booking_text,
    counterparty,
    counterparty_iban
FROM transactions
WHERE household_id = $1
  AND account_id IS NOT NULL
ORDER BY booking_date ASC, id ASC
`

type ListTransactionsForTransferScanRow struct {
	ID               uuid.UUID       `json:"id"`
	AccountID        pgtype.UUID     `json:"account_id"`
	BookingDate      pgtype.Date     `json:"booking_date"`
	Amount           decimal.Decimal `json:"amount"`
	Purpose          string          `json:"purpose"`
	BookingText      string          `json:"booking_text"`
	Counterparty     string          `json:"counterparty"`
	CounterpartyIban pgtype.Text     `json:"counterparty_iban"`
}

func (q *Queries) ListTransactionsForTransferScan(ctx context.Context, householdID uuid.UUID) ([]ListTransactionsForTransferScanRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsForTransferScan, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForTransferScanRow{}
	for rows.Next() {
		var i ListTransactionsForTransferScanRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.BookingDate,
			&i.Amount,
			&i.Purpose,
			&i.BookingText,
			&i.Counterparty,
			&i.CounterpartyIban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferPairLegs = `-- name: ListTransferPairLegs :many
SELECT tx_out_id, tx_in_id
FROM transfer_pairs
WHERE household_id = $1
`

type ListTransferPairLegsRow struct {
	TxOutID uuid.UUID `json:"tx_out_id"`
	TxInID  uuid.UUID `json:"tx_in_id"`
}

func (q *Queries) ListTransferPairLegs(ctx context.Context, householdID uuid.UUID) ([]ListTransferPairLegsRow, error) {
	rows, err := q.db.Query(ctx, listTransferPairLegs, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferPairLegsRow{}
	for rows.Next() {
		var i ListTransferPairLegsRow
		if err := rows.Scan(&i.TxOutID, &i.TxInID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferPairs = `-- name: ListTransferPairs :many
SELECT id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at, household_id
FROM transfer_pairs
WHERE household_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTransferPairs(ctx context.Context, householdID uuid.UUID) ([]TransferPair, error) {
	rows, err := q.db.Query(ctx, listTransferPairs, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransferPair{}
	for rows.Next() {
		var i TransferPair
		if err := rows.Scan(
			&i.ID,
			&i.TxOutID,
			&i.TxInID,
			&i.Status,
			&i.Confidence,
			&i.Rationale,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.HouseholdID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectTransferPair = `-- name: RejectTransferPair :one
UPDATE transfer_pairs
SET
    status = 'rejected',
    confirmed_at = NULL
WHERE id = $1
  AND household_id = $2
  AND status = 'suggested'
RETURNING id, tx_out_id, tx_in_id, status, confidence, rationale, confirmed_at, created_at, household_id
`

type RejectTransferPairParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) RejectTransferPair(ctx context.Context, arg RejectTransferPairParams) (TransferPair, error) {
	row := q.db.QueryRow(ctx, rejectTransferPair, arg.ID, arg.HouseholdID)
	var i TransferPair
	err := row.Scan(
		&i.ID,
		&i.TxOutID,
		&i.TxInID,
		&i.Status,
		&i.Confidence,
		&i.Rationale,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.HouseholdID,
	)
	return i, err
}
