// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, GetLlmModelsData, GetLlmModelsErrors, GetLlmModelsResponses, GetTransactionsData, GetTransactionsErrors, GetTransactionsResponses, PostChatData, PostChatErrors, PostChatResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List transactions
 */
export const getTransactions = <ThrowOnError extends boolean = false>(options?: Options<GetTransactionsData, ThrowOnError>): RequestResult<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError> => (options?.client ?? client).get<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError>({ url: '/api/transactions', ...options });

/**
 * Send a chat message and receive a grounded finance answer
 */
export const postChat = <ThrowOnError extends boolean = false>(options: Options<PostChatData, ThrowOnError>): RequestResult<PostChatResponses, PostChatErrors, ThrowOnError> => (options.client ?? client).post<PostChatResponses, PostChatErrors, ThrowOnError>({
    url: '/api/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List available LLM models for chat
 */
export const getLlmModels = <ThrowOnError extends boolean = false>(options?: Options<GetLlmModelsData, ThrowOnError>): RequestResult<GetLlmModelsResponses, GetLlmModelsErrors, ThrowOnError> => (options?.client ?? client).get<GetLlmModelsResponses, GetLlmModelsErrors, ThrowOnError>({ url: '/api/llm/models', ...options });
