// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type ServerSentEventsResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, GetImportData, GetImportErrors, GetImportResponses, GetImportsData, GetImportsErrors, GetImportsResponses, GetLlmModelsData, GetLlmModelsErrors, GetLlmModelsResponses, GetTransactionsData, GetTransactionsErrors, GetTransactionsResponses, GetTransferCandidatesData, GetTransferCandidatesResponses, PostChatData, PostChatErrors, PostChatResponses, PostChatStreamData, PostChatStreamErrors, PostChatStreamResponse, PostChatStreamResponses, PostImportRollbackData, PostImportRollbackErrors, PostImportRollbackResponses, PostImportsData, PostImportsErrors, PostImportsPreviewData, PostImportsPreviewErrors, PostImportsPreviewResponses, PostImportsResponses, PostTransferConfirmData, PostTransferConfirmErrors, PostTransferConfirmResponses, PostTransferRejectData, PostTransferRejectErrors, PostTransferRejectResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List transactions
 */
export const getTransactions = <ThrowOnError extends boolean = false>(options?: Options<GetTransactionsData, ThrowOnError>): RequestResult<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError> => (options?.client ?? client).get<GetTransactionsResponses, GetTransactionsErrors, ThrowOnError>({ url: '/api/transactions', ...options });

/**
 * Send a chat message and receive a grounded finance answer
 */
export const postChat = <ThrowOnError extends boolean = false>(options: Options<PostChatData, ThrowOnError>): RequestResult<PostChatResponses, PostChatErrors, ThrowOnError> => (options.client ?? client).post<PostChatResponses, PostChatErrors, ThrowOnError>({
    url: '/api/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream a grounded finance answer as server-sent events
 */
export const postChatStream = <ThrowOnError extends boolean = false>(options: Options<PostChatStreamData, ThrowOnError, PostChatStreamResponse>): Promise<ServerSentEventsResult<PostChatStreamResponses>> => (options.client ?? client).sse.post<PostChatStreamResponses, PostChatStreamErrors, ThrowOnError>({
    url: '/api/chat/stream',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List available LLM models for chat
 */
export const getLlmModels = <ThrowOnError extends boolean = false>(options?: Options<GetLlmModelsData, ThrowOnError>): RequestResult<GetLlmModelsResponses, GetLlmModelsErrors, ThrowOnError> => (options?.client ?? client).get<GetLlmModelsResponses, GetLlmModelsErrors, ThrowOnError>({ url: '/api/llm/models', ...options });

/**
 * Preview a Sparkasse CSV import without writing transactions
 */
export const postImportsPreview = <ThrowOnError extends boolean = false>(options: Options<PostImportsPreviewData, ThrowOnError>): RequestResult<PostImportsPreviewResponses, PostImportsPreviewErrors, ThrowOnError> => (options.client ?? client).post<PostImportsPreviewResponses, PostImportsPreviewErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/imports/preview',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * List recent import runs
 */
export const getImports = <ThrowOnError extends boolean = false>(options?: Options<GetImportsData, ThrowOnError>): RequestResult<GetImportsResponses, GetImportsErrors, ThrowOnError> => (options?.client ?? client).get<GetImportsResponses, GetImportsErrors, ThrowOnError>({ url: '/api/imports', ...options });

/**
 * Commit a Sparkasse CSV import
 */
export const postImports = <ThrowOnError extends boolean = false>(options: Options<PostImportsData, ThrowOnError>): RequestResult<PostImportsResponses, PostImportsErrors, ThrowOnError> => (options.client ?? client).post<PostImportsResponses, PostImportsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/imports',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Get an import run by id
 */
export const getImport = <ThrowOnError extends boolean = false>(options: Options<GetImportData, ThrowOnError>): RequestResult<GetImportResponses, GetImportErrors, ThrowOnError> => (options.client ?? client).get<GetImportResponses, GetImportErrors, ThrowOnError>({ url: '/api/imports/{id}', ...options });

/**
 * Roll back a committed import run and delete its transactions
 */
export const postImportRollback = <ThrowOnError extends boolean = false>(options: Options<PostImportRollbackData, ThrowOnError>): RequestResult<PostImportRollbackResponses, PostImportRollbackErrors, ThrowOnError> => (options.client ?? client).post<PostImportRollbackResponses, PostImportRollbackErrors, ThrowOnError>({ url: '/api/imports/{id}/rollback', ...options });

/**
 * List suggested internal transfer pairs awaiting review
 */
export const getTransferCandidates = <ThrowOnError extends boolean = false>(options?: Options<GetTransferCandidatesData, ThrowOnError>): RequestResult<GetTransferCandidatesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetTransferCandidatesResponses, unknown, ThrowOnError>({ url: '/api/transfers/candidates', ...options });

/**
 * Confirm a suggested transfer pair (exclude legs from household cashflow)
 */
export const postTransferConfirm = <ThrowOnError extends boolean = false>(options: Options<PostTransferConfirmData, ThrowOnError>): RequestResult<PostTransferConfirmResponses, PostTransferConfirmErrors, ThrowOnError> => (options.client ?? client).post<PostTransferConfirmResponses, PostTransferConfirmErrors, ThrowOnError>({ url: '/api/transfers/{id}/confirm', ...options });

/**
 * Reject a suggested transfer pair
 */
export const postTransferReject = <ThrowOnError extends boolean = false>(options: Options<PostTransferRejectData, ThrowOnError>): RequestResult<PostTransferRejectResponses, PostTransferRejectErrors, ThrowOnError> => (options.client ?? client).post<PostTransferRejectResponses, PostTransferRejectErrors, ThrowOnError>({ url: '/api/transfers/{id}/reject', ...options });
