// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Error = {
    error: string;
    message: string;
};

export type HealthResponse = {
    status: string;
};

export type Pagination = {
    limit: number;
    offset: number;
    total: number;
};

export type Transaction = {
    id: string;
    order_account: string;
    booking_date: string;
    value_date: string;
    booking_text: string;
    purpose: string;
    creditor_id: string;
    mandate_reference: string;
    end_to_end_reference: string;
    collection_reference: string;
    direct_debit_original_amount: string;
    chargeback_expense_reimbursement: string;
    counterparty: string;
    counterparty_iban?: string | null;
    counterparty_bic?: string | null;
    amount: string;
    currency: string;
    info: string;
};

export type TransactionListResponse = {
    data: Array<Transaction>;
    pagination: Pagination;
};

export type ChatRequest = {
    messages: Array<ChatMessage>;
    /**
     * Optional LLM provider override
     */
    provider?: 'ollama' | 'openrouter';
    /**
     * Optional model override for the selected provider
     */
    model?: string;
};

export type ChatMessage = {
    role: 'system' | 'user' | 'assistant';
    content: string;
};

export type ChatResponse = {
    answer: string;
    tool_calls: Array<ChatToolCall>;
};

export type ChatToolCall = {
    name: string;
    input: {
        [key: string]: unknown;
    };
    result: {
        [key: string]: unknown;
    };
};

export type LlmModelSelection = {
    provider: 'ollama' | 'openrouter';
    model: string;
};

export type LlmModelOption = {
    provider: 'ollama' | 'openrouter';
    model: string;
    label: string;
    /**
     * Optional UI group, e.g. Cloud or Local
     */
    group?: string;
};

export type LlmModelCatalog = {
    default: LlmModelSelection;
    options: Array<LlmModelOption>;
};

export type ImportPreviewPeriod = {
    from: string;
    to: string;
};

export type ImportPreviewSampleRow = {
    line: number;
    booking_date: string;
    counterparty: string;
    purpose: string;
    amount: string;
    currency: string;
};

export type ImportPreviewInvalidRow = {
    line: number;
    field?: string;
    message: string;
};

export type ImportPreviewResponse = {
    file_hash: string;
    source_filename: string;
    parser_name: string;
    parser_version: string;
    period?: ImportPreviewPeriod;
    suggested_account: string;
    row_total: number;
    row_valid: number;
    row_invalid: number;
    sample_rows: Array<ImportPreviewSampleRow>;
    invalid_rows: Array<ImportPreviewInvalidRow>;
    warnings: Array<string>;
};

export type ImportCommitResponse = {
    import_run_id: string;
    account_id: string;
    account_name: string;
    rows: number;
    inserted: number;
    duplicates: number;
};

export type ImportRun = {
    id: string;
    account_id: string;
    source_filename: string;
    status: 'committed' | 'rolled_back' | 'failed';
    row_total: number;
    row_valid: number;
    row_inserted: number;
    row_duplicate: number;
    created_at: string;
    committed_at?: string | null;
    rolled_back_at?: string | null;
};

export type ImportRunListResponse = {
    data: Array<ImportRun>;
};

export type ImportRollbackResponse = {
    import_run_id: string;
    deleted: number;
    source_filename: string;
};

export type TransferLeg = {
    transaction_id: string;
    account_name: string;
    booking_date: string;
    amount: string;
    booking_text: string;
    purpose: string;
    counterparty: string;
};

export type TransferCandidate = {
    id: string;
    status: 'suggested' | 'confirmed' | 'rejected';
    confidence: 'exact' | 'probable';
    /**
     * Absolute transfer amount in EUR
     */
    amount: string;
    out: TransferLeg;
    in: TransferLeg;
    created_at: string;
};

export type TransferCandidateListResponse = {
    data: Array<TransferCandidate>;
};

export type TransferPair = {
    id: string;
    tx_out_id: string;
    tx_in_id: string;
    status: 'suggested' | 'confirmed' | 'rejected';
    confidence: 'exact' | 'probable';
    created_at: string;
    confirmed_at?: string | null;
};

export type Category = {
    id: string;
    slug: string;
    display_name: string;
    kind: string;
    is_system: boolean;
};

export type CategoryListResponse = {
    data: Array<Category>;
};

export type ClassificationQueueItem = {
    transaction_id: string;
    booking_date: string;
    amount: string;
    counterparty: string;
    purpose: string;
    booking_text: string;
    category_slug: string;
    category_name: string;
    source: string;
    confidence: string;
    merchant_id?: string | null;
    merchant_name: string;
};

export type ClassificationQueueListResponse = {
    data: Array<ClassificationQueueItem>;
};

export type ClassificationCorrectRequest = {
    category_slug: string;
    apply_to_merchant?: boolean;
};

export type ClassificationCorrectResponse = {
    transaction_id: string;
    category_slug: string;
    rule_created: boolean;
    merchant_id?: string | null;
};

export type ClassificationApplySuggestionsResponse = {
    applied: number;
    skipped: number;
    samples: Array<ClassificationApplySuggestionSample>;
};

export type ClassificationApplySuggestionSample = {
    transaction_id: string;
    category_slug: string;
    pattern: string;
    confidence: string;
};

export type RecurringSeries = {
    id: string;
    display_name: string;
    interval: 'monthly' | 'quarterly' | 'yearly';
    kind: 'fixed' | 'variable_regular' | 'income';
    status: 'active' | 'uncertain' | 'ended';
    amount_typical: string;
    amount_last: string;
    amount_changed: boolean;
    next_expected?: string | null;
    uncertainty: 'low' | 'medium' | 'high';
    member_count: number;
    created_at: string;
};

export type RecurringSeriesListResponse = {
    data: Array<RecurringSeries>;
};

export type RecurringSeriesMember = {
    transaction_id: string;
    booking_date: string;
    amount: string;
    counterparty: string;
    purpose: string;
};

export type RecurringSeriesMembersResponse = {
    data: Array<RecurringSeriesMember>;
};

export type BaselineMetric = {
    key: 'regular_monthly_income' | 'monthly_fixed_costs' | 'monthly_irregular_costs' | 'avg_variable_spend' | 'sustainable_free_cashflow';
    value: string;
    calculation: string;
    confidence: 'high' | 'medium' | 'low';
    evidence_ids: Array<string>;
    assumptions?: Array<string>;
};

export type FinancialBaseline = {
    id: string;
    period_from: string;
    period_to: string;
    algorithm_version: string;
    status: 'draft' | 'confirmed' | 'superseded';
    regular_monthly_income: string;
    monthly_fixed_costs: string;
    monthly_irregular_costs: string;
    avg_variable_spend: string;
    sustainable_free_cashflow: string;
    confidence: 'high' | 'medium' | 'low';
    assumptions: Array<string>;
    metrics: Array<BaselineMetric>;
    confirmed_at?: string | null;
    created_at: string;
};

export type BaselineMonthlyCashflowPoint = {
    month_start: string;
    income: string;
    expenses: string;
    net: string;
};

export type BaselineMonthlyCashflowResponse = {
    data: Array<BaselineMonthlyCashflowPoint>;
};

export type BaselineRecomputeRequest = {
    /**
     * Inclusive period start (optional; requires to)
     */
    from?: string;
    /**
     * Inclusive period end (optional; requires from)
     */
    to?: string;
};

export type BaselineAdjustRequest = {
    metric_key: 'regular_monthly_income' | 'monthly_fixed_costs' | 'monthly_irregular_costs' | 'avg_variable_spend' | 'sustainable_free_cashflow';
    new_value: string;
    reason: string;
};

export type MoneyReviewFinding = {
    type: 'free_cashflow_pressure' | 'recurring_amount_change' | 'large_expense' | 'uncertain_recurring' | 'needs_review_residue';
    title: string;
    amount?: string | null;
    period_from: string;
    period_to: string;
    confidence: 'high' | 'medium' | 'low';
    evidence_ids: Array<string>;
    suggested_action_key?: string;
};

export type MoneyReview = {
    id: string;
    baseline_id: string;
    period_from: string;
    period_to: string;
    status: 'draft' | 'needs_confirmation' | 'confirmed' | 'superseded';
    summary: string;
    findings: Array<MoneyReviewFinding>;
    data_freshness: string;
    confirmed_at?: string | null;
    created_at: string;
};

export type MoneyReviewListResponse = {
    data: Array<MoneyReview>;
};

export type MoneyReviewCreateRequest = {
    /**
     * Optional; defaults to current baseline
     */
    baseline_id?: string;
};

export type ForecastPoint = {
    date: string;
    balance: string;
};

export type ForecastSeriesOption = {
    id: string;
    display_name: string;
    kind: string;
    interval: string;
    amount: string;
    enabled: boolean;
};

export type ForecastAssumptions = {
    disabled_series_ids: Array<string>;
    include_variable: boolean;
    include_uncertain: boolean;
};

export type Forecast = {
    id: string;
    baseline_id: string;
    horizon_days: number;
    starting_balance: string;
    assumptions: ForecastAssumptions;
    points: Array<ForecastPoint>;
    min_balance: string;
    ending_balance: string;
    algorithm_version: string;
    series_options: Array<ForecastSeriesOption>;
    created_at: string;
};

export type ForecastCreateRequest = {
    baseline_id?: string;
    starting_balance: string;
    horizon_days?: number;
    assumptions?: ForecastAssumptions;
};

export type Scenario = {
    id: string;
    forecast_id: string;
    kind: 'new_monthly_obligation' | 'income_gap' | 'one_off_plus_goal';
    params: {
        [key: string]: unknown;
    };
    result: ScenarioResult;
    status: 'proposed' | 'confirmed' | 'discarded';
    created_at: string;
};

export type ScenarioResult = {
    kind: string;
    min_balance: string;
    ending_balance: string;
    free_cashflow_delta: string;
    goal_feasible?: boolean | null;
    projected_at_by_date?: string | null;
    baseline_min_balance: string;
    notes: Array<string>;
};

export type ScenarioListResponse = {
    data: Array<Scenario>;
};

export type ScenarioCreateRequest = {
    kind: 'new_monthly_obligation' | 'income_gap' | 'one_off_plus_goal';
    /**
     * Kind-specific params (amounts as strings, dates as YYYY-MM-DD)
     */
    params: {
        [key: string]: unknown;
    };
};

export type Decision = {
    id: string;
    review_id?: string | null;
    scenario_id?: string | null;
    title: string;
    assumptions: {
        [key: string]: unknown;
    };
    /**
     * Optional numeric target (EUR string)
     */
    target_value?: string | null;
    decided_at: string;
    created_at: string;
    action: Action;
};

export type DecisionListResponse = {
    data: Array<Decision>;
};

export type DecisionCreateRequest = {
    review_id?: string;
    scenario_id?: string;
    title: string;
    assumptions?: {
        [key: string]: unknown;
    };
    /**
     * Optional numeric target (EUR string)
     */
    target_value?: string;
    action: ActionCreateRequest;
};

export type Action = {
    id: string;
    decision_id: string;
    title: string;
    /**
     * Expected annual EUR effect (string decimal)
     */
    expected_annual_effect: string;
    due_on: string;
    status: 'planned' | 'done' | 'skipped' | 'irrelevant';
    outcome_note: string;
    verified_at?: string | null;
    created_at: string;
    updated_at: string;
};

export type ActionListResponse = {
    data: Array<Action>;
};

export type ActionCreateRequest = {
    title: string;
    expected_annual_effect: string;
    due_on: string;
};

export type ActionStatusRequest = {
    status: 'planned' | 'done' | 'skipped' | 'irrelevant';
    outcome_note?: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        /**
         * Booking date lower bound (inclusive), YYYY-MM-DD
         */
        from?: string;
        /**
         * Booking date upper bound (inclusive), YYYY-MM-DD
         */
        to?: string;
        /**
         * Filter by order account (exact match)
         */
        account?: string;
        /**
         * Filter by counterparty name prefix
         */
        counterparty?: string;
        /**
         * Minimum amount (inclusive)
         */
        min_amount?: string;
        /**
         * Maximum amount (inclusive)
         */
        max_amount?: string;
        /**
         * Sort field
         */
        sort?: 'booking_date' | 'amount' | 'counterparty';
        /**
         * Sort direction
         */
        order?: 'asc' | 'desc';
        /**
         * Search purpose, counterparty, and booking text
         */
        q?: string;
    };
    url: '/api/transactions';
};

export type GetTransactionsErrors = {
    /**
     * Invalid request
     */
    400: Error;
};

export type GetTransactionsError = GetTransactionsErrors[keyof GetTransactionsErrors];

export type GetTransactionsResponses = {
    /**
     * Paginated transactions
     */
    200: TransactionListResponse;
};

export type GetTransactionsResponse = GetTransactionsResponses[keyof GetTransactionsResponses];

export type PostChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat';
};

export type PostChatErrors = {
    /**
     * Invalid request
     */
    400: Error;
    /**
     * Internal error
     */
    500: Error;
};

export type PostChatError = PostChatErrors[keyof PostChatErrors];

export type PostChatResponses = {
    /**
     * Assistant answer with optional tool call trace
     */
    200: ChatResponse;
};

export type PostChatResponse = PostChatResponses[keyof PostChatResponses];

export type PostChatStreamData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/api/chat/stream';
};

export type PostChatStreamErrors = {
    /**
     * Invalid request
     */
    400: Error;
    /**
     * Internal error
     */
    500: Error;
};

export type PostChatStreamError = PostChatStreamErrors[keyof PostChatStreamErrors];

export type PostChatStreamResponses = {
    /**
     * SSE stream. Events: delta, tool_start, tool_result, done, error.
     *
     */
    200: string;
};

export type PostChatStreamResponse = PostChatStreamResponses[keyof PostChatStreamResponses];

export type GetLlmModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/llm/models';
};

export type GetLlmModelsErrors = {
    /**
     * Internal error
     */
    500: Error;
};

export type GetLlmModelsError = GetLlmModelsErrors[keyof GetLlmModelsErrors];

export type GetLlmModelsResponses = {
    /**
     * Model catalog for the chat composer
     */
    200: LlmModelCatalog;
};

export type GetLlmModelsResponse = GetLlmModelsResponses[keyof GetLlmModelsResponses];

export type PostImportsPreviewData = {
    body: {
        /**
         * Sparkasse CSV export
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/imports/preview';
};

export type PostImportsPreviewErrors = {
    /**
     * Invalid request or unreadable CSV
     */
    400: Error;
};

export type PostImportsPreviewError = PostImportsPreviewErrors[keyof PostImportsPreviewErrors];

export type PostImportsPreviewResponses = {
    /**
     * Import preview with stats, samples, and validation errors
     */
    200: ImportPreviewResponse;
};

export type PostImportsPreviewResponse = PostImportsPreviewResponses[keyof PostImportsPreviewResponses];

export type GetImportsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/imports';
};

export type GetImportsErrors = {
    /**
     * Invalid request
     */
    400: Error;
};

export type GetImportsError = GetImportsErrors[keyof GetImportsErrors];

export type GetImportsResponses = {
    /**
     * Recent import runs
     */
    200: ImportRunListResponse;
};

export type GetImportsResponse = GetImportsResponses[keyof GetImportsResponses];

export type PostImportsData = {
    body: {
        /**
         * Sparkasse CSV export
         */
        file: Blob | File;
        /**
         * Display name for a new or matched account
         */
        account_name?: string;
        /**
         * Existing account to attach the import run to
         */
        account_id?: string;
        /**
         * Optional SHA-256 from preview; must match the uploaded file
         */
        preview_hash?: string;
    };
    path?: never;
    query?: never;
    url: '/api/imports';
};

export type PostImportsErrors = {
    /**
     * Invalid request, unreadable CSV, or preview hash mismatch
     */
    400: Error;
};

export type PostImportsError = PostImportsErrors[keyof PostImportsErrors];

export type PostImportsResponses = {
    /**
     * Import committed
     */
    201: ImportCommitResponse;
};

export type PostImportsResponse = PostImportsResponses[keyof PostImportsResponses];

export type GetImportData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/imports/{id}';
};

export type GetImportErrors = {
    /**
     * Import run not found
     */
    404: Error;
};

export type GetImportError = GetImportErrors[keyof GetImportErrors];

export type GetImportResponses = {
    /**
     * Import run
     */
    200: ImportRun;
};

export type GetImportResponse = GetImportResponses[keyof GetImportResponses];

export type PostImportRollbackData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/imports/{id}/rollback';
};

export type PostImportRollbackErrors = {
    /**
     * Import run not found
     */
    404: Error;
    /**
     * Import run already rolled back or not committed
     */
    409: Error;
};

export type PostImportRollbackError = PostImportRollbackErrors[keyof PostImportRollbackErrors];

export type PostImportRollbackResponses = {
    /**
     * Import run rolled back
     */
    200: ImportRollbackResponse;
};

export type PostImportRollbackResponse = PostImportRollbackResponses[keyof PostImportRollbackResponses];

export type GetTransferCandidatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/transfers/candidates';
};

export type GetTransferCandidatesResponses = {
    /**
     * Suggested transfer candidates
     */
    200: TransferCandidateListResponse;
};

export type GetTransferCandidatesResponse = GetTransferCandidatesResponses[keyof GetTransferCandidatesResponses];

export type PostTransferConfirmData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/transfers/{id}/confirm';
};

export type PostTransferConfirmErrors = {
    /**
     * Transfer pair not found
     */
    404: Error;
    /**
     * Transfer pair is not in suggested status
     */
    409: Error;
};

export type PostTransferConfirmError = PostTransferConfirmErrors[keyof PostTransferConfirmErrors];

export type PostTransferConfirmResponses = {
    /**
     * Transfer pair confirmed
     */
    200: TransferPair;
};

export type PostTransferConfirmResponse = PostTransferConfirmResponses[keyof PostTransferConfirmResponses];

export type PostTransferRejectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/transfers/{id}/reject';
};

export type PostTransferRejectErrors = {
    /**
     * Transfer pair not found
     */
    404: Error;
    /**
     * Transfer pair is not in suggested status
     */
    409: Error;
};

export type PostTransferRejectError = PostTransferRejectErrors[keyof PostTransferRejectErrors];

export type PostTransferRejectResponses = {
    /**
     * Transfer pair rejected
     */
    200: TransferPair;
};

export type PostTransferRejectResponse = PostTransferRejectResponses[keyof PostTransferRejectResponses];

export type GetUncertainRecurringData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/recurring/uncertain';
};

export type GetUncertainRecurringResponses = {
    /**
     * Uncertain recurring series
     */
    200: RecurringSeriesListResponse;
};

export type GetUncertainRecurringResponse = GetUncertainRecurringResponses[keyof GetUncertainRecurringResponses];

export type GetRecurringMembersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
    };
    url: '/api/recurring/{id}/members';
};

export type GetRecurringMembersErrors = {
    /**
     * Recurring series not found
     */
    404: Error;
};

export type GetRecurringMembersError = GetRecurringMembersErrors[keyof GetRecurringMembersErrors];

export type GetRecurringMembersResponses = {
    /**
     * Recent member transactions
     */
    200: RecurringSeriesMembersResponse;
};

export type GetRecurringMembersResponse = GetRecurringMembersResponses[keyof GetRecurringMembersResponses];

export type PostRecurringConfirmData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/recurring/{id}/confirm';
};

export type PostRecurringConfirmErrors = {
    /**
     * Recurring series not found
     */
    404: Error;
    /**
     * Recurring series is not uncertain
     */
    409: Error;
};

export type PostRecurringConfirmError = PostRecurringConfirmErrors[keyof PostRecurringConfirmErrors];

export type PostRecurringConfirmResponses = {
    /**
     * Recurring series confirmed
     */
    200: RecurringSeries;
};

export type PostRecurringConfirmResponse = PostRecurringConfirmResponses[keyof PostRecurringConfirmResponses];

export type PostRecurringRejectData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/recurring/{id}/reject';
};

export type PostRecurringRejectErrors = {
    /**
     * Recurring series not found
     */
    404: Error;
    /**
     * Recurring series is not uncertain
     */
    409: Error;
};

export type PostRecurringRejectError = PostRecurringRejectErrors[keyof PostRecurringRejectErrors];

export type PostRecurringRejectResponses = {
    /**
     * Recurring series dismissed
     */
    200: RecurringSeries;
};

export type PostRecurringRejectResponse = PostRecurringRejectResponses[keyof PostRecurringRejectResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/categories';
};

export type GetCategoriesResponses = {
    /**
     * Category taxonomy
     */
    200: CategoryListResponse;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetClassificationQueueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/classifications/queue';
};

export type GetClassificationQueueResponses = {
    /**
     * Classification queue items
     */
    200: ClassificationQueueListResponse;
};

export type GetClassificationQueueResponse = GetClassificationQueueResponses[keyof GetClassificationQueueResponses];

export type PostClassificationApplySuggestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/classifications/apply-suggestions';
};

export type PostClassificationApplySuggestionsResponses = {
    /**
     * Suggestions applied
     */
    200: ClassificationApplySuggestionsResponse;
};

export type PostClassificationApplySuggestionsResponse = PostClassificationApplySuggestionsResponses[keyof PostClassificationApplySuggestionsResponses];

export type PostClassificationCorrectData = {
    body: ClassificationCorrectRequest;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/api/classifications/{transaction_id}/correct';
};

export type PostClassificationCorrectErrors = {
    /**
     * Invalid category or request
     */
    400: Error;
    /**
     * Transaction not found
     */
    404: Error;
};

export type PostClassificationCorrectError = PostClassificationCorrectErrors[keyof PostClassificationCorrectErrors];

export type PostClassificationCorrectResponses = {
    /**
     * Classification corrected
     */
    200: ClassificationCorrectResponse;
};

export type PostClassificationCorrectResponse = PostClassificationCorrectResponses[keyof PostClassificationCorrectResponses];

export type GetCurrentBaselineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/baselines/current';
};

export type GetCurrentBaselineErrors = {
    /**
     * No baseline available
     */
    404: Error;
};

export type GetCurrentBaselineError = GetCurrentBaselineErrors[keyof GetCurrentBaselineErrors];

export type GetCurrentBaselineResponses = {
    /**
     * Current baseline
     */
    200: FinancialBaseline;
};

export type GetCurrentBaselineResponse = GetCurrentBaselineResponses[keyof GetCurrentBaselineResponses];

export type GetBaselineMonthlyCashflowData = {
    body?: never;
    path?: never;
    query?: {
        months?: number;
    };
    url: '/api/baselines/monthly-cashflow';
};

export type GetBaselineMonthlyCashflowResponses = {
    /**
     * Monthly cashflow series
     */
    200: BaselineMonthlyCashflowResponse;
};

export type GetBaselineMonthlyCashflowResponse = GetBaselineMonthlyCashflowResponses[keyof GetBaselineMonthlyCashflowResponses];

export type PostBaselinesRecomputeData = {
    body?: BaselineRecomputeRequest;
    path?: never;
    query?: never;
    url: '/api/baselines/recompute';
};

export type PostBaselinesRecomputeErrors = {
    /**
     * Invalid period
     */
    400: Error;
};

export type PostBaselinesRecomputeError = PostBaselinesRecomputeErrors[keyof PostBaselinesRecomputeErrors];

export type PostBaselinesRecomputeResponses = {
    /**
     * Draft baseline created
     */
    200: FinancialBaseline;
};

export type PostBaselinesRecomputeResponse = PostBaselinesRecomputeResponses[keyof PostBaselinesRecomputeResponses];

export type PostBaselineConfirmData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/baselines/{id}/confirm';
};

export type PostBaselineConfirmErrors = {
    /**
     * Baseline not found
     */
    404: Error;
    /**
     * Baseline is not in draft status
     */
    409: Error;
};

export type PostBaselineConfirmError = PostBaselineConfirmErrors[keyof PostBaselineConfirmErrors];

export type PostBaselineConfirmResponses = {
    /**
     * Baseline confirmed
     */
    200: FinancialBaseline;
};

export type PostBaselineConfirmResponse = PostBaselineConfirmResponses[keyof PostBaselineConfirmResponses];

export type PostBaselineAdjustData = {
    body: BaselineAdjustRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/baselines/{id}/adjust';
};

export type PostBaselineAdjustErrors = {
    /**
     * Invalid adjustment
     */
    400: Error;
    /**
     * Baseline not found
     */
    404: Error;
    /**
     * Baseline cannot be adjusted
     */
    409: Error;
};

export type PostBaselineAdjustError = PostBaselineAdjustErrors[keyof PostBaselineAdjustErrors];

export type PostBaselineAdjustResponses = {
    /**
     * Adjusted draft baseline
     */
    200: FinancialBaseline;
};

export type PostBaselineAdjustResponse = PostBaselineAdjustResponses[keyof PostBaselineAdjustResponses];

export type GetMoneyReviewsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/reviews';
};

export type GetMoneyReviewsResponses = {
    /**
     * Money Review history
     */
    200: MoneyReviewListResponse;
};

export type GetMoneyReviewsResponse = GetMoneyReviewsResponses[keyof GetMoneyReviewsResponses];

export type PostMoneyReviewsData = {
    body?: MoneyReviewCreateRequest;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type PostMoneyReviewsErrors = {
    /**
     * Baseline missing or invalid request
     */
    400: Error;
    /**
     * Baseline not found
     */
    404: Error;
};

export type PostMoneyReviewsError = PostMoneyReviewsErrors[keyof PostMoneyReviewsErrors];

export type PostMoneyReviewsResponses = {
    /**
     * Money Review created
     */
    200: MoneyReview;
};

export type PostMoneyReviewsResponse = PostMoneyReviewsResponses[keyof PostMoneyReviewsResponses];

export type GetMoneyReviewData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type GetMoneyReviewErrors = {
    /**
     * Review not found
     */
    404: Error;
};

export type GetMoneyReviewError = GetMoneyReviewErrors[keyof GetMoneyReviewErrors];

export type GetMoneyReviewResponses = {
    /**
     * Money Review
     */
    200: MoneyReview;
};

export type GetMoneyReviewResponse = GetMoneyReviewResponses[keyof GetMoneyReviewResponses];

export type PostMoneyReviewConfirmData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}/confirm';
};

export type PostMoneyReviewConfirmErrors = {
    /**
     * Review not found
     */
    404: Error;
    /**
     * Review cannot be confirmed
     */
    409: Error;
};

export type PostMoneyReviewConfirmError = PostMoneyReviewConfirmErrors[keyof PostMoneyReviewConfirmErrors];

export type PostMoneyReviewConfirmResponses = {
    /**
     * Review confirmed
     */
    200: MoneyReview;
};

export type PostMoneyReviewConfirmResponse = PostMoneyReviewConfirmResponses[keyof PostMoneyReviewConfirmResponses];

export type PostForecastsData = {
    body: ForecastCreateRequest;
    path?: never;
    query?: never;
    url: '/api/forecasts';
};

export type PostForecastsErrors = {
    /**
     * Invalid request or missing baseline
     */
    400: Error;
    /**
     * Baseline not found
     */
    404: Error;
};

export type PostForecastsError = PostForecastsErrors[keyof PostForecastsErrors];

export type PostForecastsResponses = {
    /**
     * Forecast created
     */
    200: Forecast;
};

export type PostForecastsResponse = PostForecastsResponses[keyof PostForecastsResponses];

export type GetLatestForecastData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/forecasts/latest';
};

export type GetLatestForecastErrors = {
    /**
     * No forecast available
     */
    404: Error;
};

export type GetLatestForecastError = GetLatestForecastErrors[keyof GetLatestForecastErrors];

export type GetLatestForecastResponses = {
    /**
     * Latest forecast
     */
    200: Forecast;
};

export type GetLatestForecastResponse = GetLatestForecastResponses[keyof GetLatestForecastResponses];

export type GetForecastData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecasts/{id}';
};

export type GetForecastErrors = {
    /**
     * Forecast not found
     */
    404: Error;
};

export type GetForecastError = GetForecastErrors[keyof GetForecastErrors];

export type GetForecastResponses = {
    /**
     * Forecast
     */
    200: Forecast;
};

export type GetForecastResponse = GetForecastResponses[keyof GetForecastResponses];

export type GetForecastScenariosData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecasts/{id}/scenarios';
};

export type GetForecastScenariosResponses = {
    /**
     * Scenarios
     */
    200: ScenarioListResponse;
};

export type GetForecastScenariosResponse = GetForecastScenariosResponses[keyof GetForecastScenariosResponses];

export type PostForecastScenarioData = {
    body: ScenarioCreateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/forecasts/{id}/scenarios';
};

export type PostForecastScenarioErrors = {
    /**
     * Invalid scenario
     */
    400: Error;
    /**
     * Forecast not found
     */
    404: Error;
};

export type PostForecastScenarioError = PostForecastScenarioErrors[keyof PostForecastScenarioErrors];

export type PostForecastScenarioResponses = {
    /**
     * Scenario result
     */
    200: Scenario;
};

export type PostForecastScenarioResponse = PostForecastScenarioResponses[keyof PostForecastScenarioResponses];

export type GetDecisionsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
    };
    url: '/api/decisions';
};

export type GetDecisionsResponses = {
    /**
     * Decision history
     */
    200: DecisionListResponse;
};

export type GetDecisionsResponse = GetDecisionsResponses[keyof GetDecisionsResponses];

export type PostDecisionsData = {
    body: DecisionCreateRequest;
    path?: never;
    query?: never;
    url: '/api/decisions';
};

export type PostDecisionsErrors = {
    /**
     * Invalid request
     */
    400: Error;
    /**
     * Review or scenario not found
     */
    404: Error;
};

export type PostDecisionsError = PostDecisionsErrors[keyof PostDecisionsErrors];

export type PostDecisionsResponses = {
    /**
     * Decision created
     */
    200: Decision;
};

export type PostDecisionsResponse = PostDecisionsResponses[keyof PostDecisionsResponses];

export type GetActionsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'planned' | 'done' | 'skipped' | 'irrelevant';
        limit?: number;
    };
    url: '/api/actions';
};

export type GetActionsResponses = {
    /**
     * Actions
     */
    200: ActionListResponse;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type PostActionStatusData = {
    body: ActionStatusRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/actions/{id}/status';
};

export type PostActionStatusErrors = {
    /**
     * Invalid status transition
     */
    400: Error;
    /**
     * Action not found
     */
    404: Error;
};

export type PostActionStatusError = PostActionStatusErrors[keyof PostActionStatusErrors];

export type PostActionStatusResponses = {
    /**
     * Action updated
     */
    200: Action;
};

export type PostActionStatusResponse = PostActionStatusResponses[keyof PostActionStatusResponses];
