// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getCategories, getClassificationQueue, getHealth, getImport, getImports, getLlmModels, getTransactions, getTransferCandidates, type Options, postChat, postClassificationCorrect, postImportRollback, postImports, postImportsPreview, postTransferConfirm, postTransferReject } from '../sdk.gen';
import type { GetCategoriesData, GetCategoriesResponse, GetClassificationQueueData, GetClassificationQueueResponse, GetHealthData, GetHealthResponse, GetImportData, GetImportError, GetImportResponse, GetImportsData, GetImportsError, GetImportsResponse, GetLlmModelsData, GetLlmModelsError, GetLlmModelsResponse, GetTransactionsData, GetTransactionsError, GetTransactionsResponse, GetTransferCandidatesData, GetTransferCandidatesResponse, PostChatData, PostChatError, PostChatResponse, PostClassificationCorrectData, PostClassificationCorrectError, PostClassificationCorrectResponse, PostImportRollbackData, PostImportRollbackError, PostImportRollbackResponse, PostImportsData, PostImportsError, PostImportsPreviewData, PostImportsPreviewError, PostImportsPreviewResponse, PostImportsResponse, PostTransferConfirmData, PostTransferConfirmError, PostTransferConfirmResponse, PostTransferRejectData, PostTransferRejectError, PostTransferRejectResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Health check
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getTransactionsQueryKey = (options?: Options<GetTransactionsData>) => createQueryKey('getTransactions', options);

/**
 * List transactions
 */
export const getTransactionsOptions = (options?: Options<GetTransactionsData>) => queryOptions<GetTransactionsResponse, GetTransactionsError, GetTransactionsResponse, ReturnType<typeof getTransactionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTransactions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransactionsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getTransactionsInfiniteQueryKey = (options?: Options<GetTransactionsData>): QueryKey<Options<GetTransactionsData>> => createQueryKey('getTransactions', options, true);

/**
 * List transactions
 */
export const getTransactionsInfiniteOptions = (options?: Options<GetTransactionsData>) => {
    const opts = infiniteQueryOptions<GetTransactionsResponse, GetTransactionsError, InfiniteData<GetTransactionsResponse>, QueryKey<Options<GetTransactionsData>>, number | Pick<QueryKey<Options<GetTransactionsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetTransactionsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getTransactions({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getTransactionsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Send a chat message and receive a grounded finance answer
 */
export const postChatMutation = (options?: Partial<Options<PostChatData>>): UseMutationOptions<PostChatResponse, PostChatError, Options<PostChatData>> => {
    const mutationOptions: UseMutationOptions<PostChatResponse, PostChatError, Options<PostChatData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postChat({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLlmModelsQueryKey = (options?: Options<GetLlmModelsData>) => createQueryKey('getLlmModels', options);

/**
 * List available LLM models for chat
 */
export const getLlmModelsOptions = (options?: Options<GetLlmModelsData>) => queryOptions<GetLlmModelsResponse, GetLlmModelsError, GetLlmModelsResponse, ReturnType<typeof getLlmModelsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLlmModels({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLlmModelsQueryKey(options)
});

/**
 * Preview a Sparkasse CSV import without writing transactions
 */
export const postImportsPreviewMutation = (options?: Partial<Options<PostImportsPreviewData>>): UseMutationOptions<PostImportsPreviewResponse, PostImportsPreviewError, Options<PostImportsPreviewData>> => {
    const mutationOptions: UseMutationOptions<PostImportsPreviewResponse, PostImportsPreviewError, Options<PostImportsPreviewData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postImportsPreview({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getImportsQueryKey = (options?: Options<GetImportsData>) => createQueryKey('getImports', options);

/**
 * List recent import runs
 */
export const getImportsOptions = (options?: Options<GetImportsData>) => queryOptions<GetImportsResponse, GetImportsError, GetImportsResponse, ReturnType<typeof getImportsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getImports({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getImportsQueryKey(options)
});

/**
 * Commit a Sparkasse CSV import
 */
export const postImportsMutation = (options?: Partial<Options<PostImportsData>>): UseMutationOptions<PostImportsResponse, PostImportsError, Options<PostImportsData>> => {
    const mutationOptions: UseMutationOptions<PostImportsResponse, PostImportsError, Options<PostImportsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postImports({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getImportQueryKey = (options: Options<GetImportData>) => createQueryKey('getImport', options);

/**
 * Get an import run by id
 */
export const getImportOptions = (options: Options<GetImportData>) => queryOptions<GetImportResponse, GetImportError, GetImportResponse, ReturnType<typeof getImportQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getImport({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getImportQueryKey(options)
});

/**
 * Roll back a committed import run and delete its transactions
 */
export const postImportRollbackMutation = (options?: Partial<Options<PostImportRollbackData>>): UseMutationOptions<PostImportRollbackResponse, PostImportRollbackError, Options<PostImportRollbackData>> => {
    const mutationOptions: UseMutationOptions<PostImportRollbackResponse, PostImportRollbackError, Options<PostImportRollbackData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postImportRollback({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTransferCandidatesQueryKey = (options?: Options<GetTransferCandidatesData>) => createQueryKey('getTransferCandidates', options);

/**
 * List suggested internal transfer pairs awaiting review
 */
export const getTransferCandidatesOptions = (options?: Options<GetTransferCandidatesData>) => queryOptions<GetTransferCandidatesResponse, DefaultError, GetTransferCandidatesResponse, ReturnType<typeof getTransferCandidatesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTransferCandidates({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransferCandidatesQueryKey(options)
});

/**
 * Confirm a suggested transfer pair (exclude legs from household cashflow)
 */
export const postTransferConfirmMutation = (options?: Partial<Options<PostTransferConfirmData>>): UseMutationOptions<PostTransferConfirmResponse, PostTransferConfirmError, Options<PostTransferConfirmData>> => {
    const mutationOptions: UseMutationOptions<PostTransferConfirmResponse, PostTransferConfirmError, Options<PostTransferConfirmData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postTransferConfirm({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reject a suggested transfer pair
 */
export const postTransferRejectMutation = (options?: Partial<Options<PostTransferRejectData>>): UseMutationOptions<PostTransferRejectResponse, PostTransferRejectError, Options<PostTransferRejectData>> => {
    const mutationOptions: UseMutationOptions<PostTransferRejectResponse, PostTransferRejectError, Options<PostTransferRejectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postTransferReject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCategoriesQueryKey = (options?: Options<GetCategoriesData>) => createQueryKey('getCategories', options);

/**
 * List system (and user) categories
 */
export const getCategoriesOptions = (options?: Options<GetCategoriesData>) => queryOptions<GetCategoriesResponse, DefaultError, GetCategoriesResponse, ReturnType<typeof getCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCategoriesQueryKey(options)
});

export const getClassificationQueueQueryKey = (options?: Options<GetClassificationQueueData>) => createQueryKey('getClassificationQueue', options);

/**
 * List high-impact classifications awaiting review
 */
export const getClassificationQueueOptions = (options?: Options<GetClassificationQueueData>) => queryOptions<GetClassificationQueueResponse, DefaultError, GetClassificationQueueResponse, ReturnType<typeof getClassificationQueueQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getClassificationQueue({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getClassificationQueueQueryKey(options)
});

/**
 * Correct a transaction category and optionally save a merchant rule
 */
export const postClassificationCorrectMutation = (options?: Partial<Options<PostClassificationCorrectData>>): UseMutationOptions<PostClassificationCorrectResponse, PostClassificationCorrectError, Options<PostClassificationCorrectData>> => {
    const mutationOptions: UseMutationOptions<PostClassificationCorrectResponse, PostClassificationCorrectError, Options<PostClassificationCorrectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postClassificationCorrect({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
